************* Module ADDMo
__init__.py:1:0: C0103: Module name "ADDMo" doesn't conform to snake_case naming style (invalid-name)
************* Module exe_model_testing
addmo_examples/executables/exe_model_testing.py:18:0: C0301: Line too long (102/100) (line-too-long)
addmo_examples/executables/exe_model_testing.py:19:0: C0301: Line too long (109/100) (line-too-long)
addmo_examples/executables/exe_model_testing.py:26:0: C0301: Line too long (162/100) (line-too-long)
addmo_examples/executables/exe_model_testing.py:27:0: C0301: Line too long (157/100) (line-too-long)
addmo_examples/executables/exe_model_testing.py:28:0: C0301: Line too long (120/100) (line-too-long)
addmo_examples/executables/exe_model_testing.py:29:0: C0301: Line too long (105/100) (line-too-long)
addmo_examples/executables/exe_model_testing.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo_examples/executables/exe_model_testing.py:29:4: W0622: Redefining built-in 'dir' (redefined-builtin)
addmo_examples/executables/exe_model_testing.py:3:0: E0401: Unable to import 'addmo.s4_model_testing.model_testing' (import-error)
addmo_examples/executables/exe_model_testing.py:4:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
addmo_examples/executables/exe_model_testing.py:5:0: E0401: Unable to import 'addmo.util.definitions' (import-error)
addmo_examples/executables/exe_model_testing.py:7:0: C0116: Missing function or method docstring (missing-function-docstring)
addmo_examples/executables/exe_model_testing.py:7:19: W0621: Redefining name 'dir' from outer scope (line 29) (redefined-outer-name)
addmo_examples/executables/exe_model_testing.py:7:24: W0621: Redefining name 'input_data_path' from outer scope (line 31) (redefined-outer-name)
addmo_examples/executables/exe_model_testing.py:7:41: W0621: Redefining name 'data_tuning_type' from outer scope (line 32) (redefined-outer-name)
addmo_examples/executables/exe_model_testing.py:11:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
addmo_examples/executables/exe_model_testing.py:11:35: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
addmo_examples/executables/exe_model_testing.py:32:4: C0103: Constant name "data_tuning_type" doesn't conform to UPPER_CASE naming style (invalid-name)
************* Module exe_data_insights
addmo_examples/executables/exe_data_insights.py:7:0: C0301: Line too long (124/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:8:0: C0301: Line too long (105/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:23:0: C0301: Line too long (109/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:25:0: C0301: Line too long (165/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:46:0: C0301: Line too long (139/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:70:0: C0301: Line too long (137/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:73:0: C0301: Line too long (116/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:83:0: C0301: Line too long (186/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:93:0: C0301: Line too long (148/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:115:0: C0301: Line too long (133/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:117:0: C0301: Line too long (165/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:127:0: C0301: Line too long (230/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:154:0: C0301: Line too long (109/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:156:0: C0301: Line too long (165/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:185:0: C0301: Line too long (133/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:187:0: C0301: Line too long (165/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:207:0: C0301: Line too long (114/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:216:0: C0301: Line too long (206/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:217:0: C0301: Line too long (116/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:218:0: C0301: Line too long (110/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:219:0: C0301: Line too long (104/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:220:0: C0301: Line too long (128/100) (line-too-long)
addmo_examples/executables/exe_data_insights.py:223:0: C0305: Trailing newlines (trailing-newlines)
addmo_examples/executables/exe_data_insights.py:216:140: W0511: Todo: Note for user: pls check input data path inside the exe func (fixme)
addmo_examples/executables/exe_data_insights.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo_examples/executables/exe_data_insights.py:2:0: C0410: Multiple imports on one line (pandas, csv) (multiple-imports)
addmo_examples/executables/exe_data_insights.py:2:0: E0401: Unable to import 'pandas' (import-error)
addmo_examples/executables/exe_data_insights.py:4:0: E0401: Unable to import 'addmo.s5_insights.model_plots.time_series' (import-error)
addmo_examples/executables/exe_data_insights.py:5:0: E0401: Unable to import 'addmo.s5_insights.model_plots.parallel_plots' (import-error)
addmo_examples/executables/exe_data_insights.py:6:0: E0401: Unable to import 'addmo.util.plotting_utils' (import-error)
addmo_examples/executables/exe_data_insights.py:7:0: E0401: Unable to import 'addmo.s5_insights.model_plots.carpet_plots' (import-error)
addmo_examples/executables/exe_data_insights.py:8:0: E0401: Unable to import 'addmo.util.definitions' (import-error)
addmo_examples/executables/exe_data_insights.py:9:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
addmo_examples/executables/exe_data_insights.py:10:0: E0401: Unable to import 'addmo.s3_model_tuning.models.model_factory' (import-error)
addmo_examples/executables/exe_data_insights.py:12:25: W0622: Redefining built-in 'dir' (redefined-builtin)
addmo_examples/executables/exe_data_insights.py:12:41: W0621: Redefining name 'plot_dir' from outer scope (line 210) (redefined-outer-name)
addmo_examples/executables/exe_data_insights.py:25:68: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
addmo_examples/executables/exe_data_insights.py:25:68: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
addmo_examples/executables/exe_data_insights.py:46:0: R0913: Too many arguments (8/5) (too-many-arguments)
addmo_examples/executables/exe_data_insights.py:46:0: R0914: Too many local variables (18/15) (too-many-locals)
addmo_examples/executables/exe_data_insights.py:46:21: W0622: Redefining built-in 'dir' (redefined-builtin)
addmo_examples/executables/exe_data_insights.py:46:37: W0621: Redefining name 'plot_dir' from outer scope (line 210) (redefined-outer-name)
addmo_examples/executables/exe_data_insights.py:73:61: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
addmo_examples/executables/exe_data_insights.py:73:61: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
addmo_examples/executables/exe_data_insights.py:93:0: R0913: Too many arguments (8/5) (too-many-arguments)
addmo_examples/executables/exe_data_insights.py:93:0: R0914: Too many local variables (19/15) (too-many-locals)
addmo_examples/executables/exe_data_insights.py:93:29: W0622: Redefining built-in 'dir' (redefined-builtin)
addmo_examples/executables/exe_data_insights.py:93:45: W0621: Redefining name 'plot_dir' from outer scope (line 210) (redefined-outer-name)
addmo_examples/executables/exe_data_insights.py:117:68: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
addmo_examples/executables/exe_data_insights.py:117:68: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
addmo_examples/executables/exe_data_insights.py:137:22: W0622: Redefining built-in 'dir' (redefined-builtin)
addmo_examples/executables/exe_data_insights.py:137:38: W0621: Redefining name 'plot_dir' from outer scope (line 210) (redefined-outer-name)
addmo_examples/executables/exe_data_insights.py:156:68: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
addmo_examples/executables/exe_data_insights.py:156:68: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
addmo_examples/executables/exe_data_insights.py:169:34: W0622: Redefining built-in 'dir' (redefined-builtin)
addmo_examples/executables/exe_data_insights.py:169:50: W0621: Redefining name 'plot_dir' from outer scope (line 210) (redefined-outer-name)
addmo_examples/executables/exe_data_insights.py:187:68: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
addmo_examples/executables/exe_data_insights.py:187:68: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
addmo_examples/executables/exe_data_insights.py:2:0: C0411: standard import "import pandas as pd, csv" should be placed before "import pandas as pd, csv" (wrong-import-order)
addmo_examples/executables/exe_data_insights.py:3:0: C0411: standard import "import datetime" should be placed before "import pandas as pd, csv" (wrong-import-order)
************* Module exe_data_tuning_auto
addmo_examples/executables/exe_data_tuning_auto.py:79:0: C0301: Line too long (165/100) (line-too-long)
addmo_examples/executables/exe_data_tuning_auto.py:80:0: C0304: Final newline missing (missing-final-newline)
addmo_examples/executables/exe_data_tuning_auto.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo_examples/executables/exe_data_tuning_auto.py:3:0: E0401: Unable to import 'pandas' (import-error)
addmo_examples/executables/exe_data_tuning_auto.py:4:0: E0401: Unable to import 'addmo.util.plotting_utils' (import-error)
addmo_examples/executables/exe_data_tuning_auto.py:5:0: E0401: Unable to import 'addmo.util.definitions' (import-error)
addmo_examples/executables/exe_data_tuning_auto.py:6:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
addmo_examples/executables/exe_data_tuning_auto.py:7:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo_examples/executables/exe_data_tuning_auto.py:8:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo_examples/executables/exe_data_tuning_auto.py:9:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo_examples/executables/exe_data_tuning_auto.py:10:0: E0401: Unable to import 'addmo.s1_data_tuning_auto.config.data_tuning_auto_config' (import-error)
addmo_examples/executables/exe_data_tuning_auto.py:11:0: E0401: Unable to import 'addmo.s1_data_tuning_auto.data_tuner_auto' (import-error)
addmo_examples/executables/exe_data_tuning_auto.py:12:0: E0401: Unable to import 'addmo.s5_insights.model_plots.time_series' (import-error)
addmo_examples/executables/exe_data_tuning_auto.py:13:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
addmo_examples/executables/exe_data_tuning_auto.py:15:0: R0914: Too many local variables (17/15) (too-many-locals)
addmo_examples/executables/exe_data_tuning_auto.py:15:34: W0621: Redefining name 'user_input' from outer scope (line 79) (redefined-outer-name)
addmo_examples/executables/exe_data_tuning_auto.py:37:4: C0103: Variable name "y" doesn't conform to snake_case naming style (invalid-name)
addmo_examples/executables/exe_data_tuning_auto.py:49:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
addmo_examples/executables/exe_data_tuning_auto.py:49:35: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
addmo_examples/executables/exe_data_tuning_auto.py:63:25: W0621: Redefining name 'user_input' from outer scope (line 79) (redefined-outer-name)
addmo_examples/executables/exe_data_tuning_auto.py:63:25: W0613: Unused argument 'user_input' (unused-argument)
addmo_examples/executables/exe_data_tuning_auto.py:73:40: W0621: Redefining name 'user_input' from outer scope (line 79) (redefined-outer-name)
addmo_examples/executables/exe_data_tuning_auto.py:73:40: W0613: Unused argument 'user_input' (unused-argument)
************* Module exe_model_tuning
addmo_examples/executables/exe_model_tuning.py:4:0: C0301: Line too long (120/100) (line-too-long)
addmo_examples/executables/exe_model_tuning.py:48:0: C0301: Line too long (117/100) (line-too-long)
addmo_examples/executables/exe_model_tuning.py:81:0: C0301: Line too long (194/100) (line-too-long)
addmo_examples/executables/exe_model_tuning.py:83:0: C0304: Final newline missing (missing-final-newline)
addmo_examples/executables/exe_model_tuning.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo_examples/executables/exe_model_tuning.py:2:0: E0401: Unable to import 'pandas' (import-error)
addmo_examples/executables/exe_model_tuning.py:4:0: E0401: Unable to import 'addmo.util.definitions' (import-error)
addmo_examples/executables/exe_model_tuning.py:5:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
addmo_examples/executables/exe_model_tuning.py:6:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo_examples/executables/exe_model_tuning.py:7:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo_examples/executables/exe_model_tuning.py:8:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo_examples/executables/exe_model_tuning.py:9:0: E0401: Unable to import 'addmo.s3_model_tuning.models.keras_models' (import-error)
addmo_examples/executables/exe_model_tuning.py:10:0: E0401: Unable to import 'addmo.s3_model_tuning.config.model_tuning_config' (import-error)
addmo_examples/executables/exe_model_tuning.py:11:0: E0401: Unable to import 'addmo.s3_model_tuning.config.model_tuning_config' (import-error)
addmo_examples/executables/exe_model_tuning.py:12:0: E0401: Unable to import 'addmo.s3_model_tuning.model_tuner' (import-error)
addmo_examples/executables/exe_model_tuning.py:13:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
addmo_examples/executables/exe_model_tuning.py:14:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
addmo_examples/executables/exe_model_tuning.py:15:0: E0401: Unable to import 'addmo.util.data_handling' (import-error)
addmo_examples/executables/exe_model_tuning.py:16:0: E0401: Unable to import 'addmo.s5_insights.model_plots.scatter_plot' (import-error)
addmo_examples/executables/exe_model_tuning.py:17:0: E0401: Unable to import 'addmo.util.plotting_utils' (import-error)
addmo_examples/executables/exe_model_tuning.py:20:21: W0621: Redefining name 'user_input' from outer scope (line 80) (redefined-outer-name)
addmo_examples/executables/exe_model_tuning.py:20:37: W0621: Redefining name 'config_exp' from outer scope (line 77) (redefined-outer-name)
addmo_examples/executables/exe_model_tuning.py:20:54: W0621: Redefining name 'config_tuner' from outer scope (line 78) (redefined-outer-name)
addmo_examples/executables/exe_model_tuning.py:4:0: W0611: Unused results_dir_data_tuning_auto imported from addmo.util.definitions (unused-import)
addmo_examples/executables/exe_model_tuning.py:4:0: W0611: Unused results_dir_data_tuning_fixed imported from addmo.util.definitions (unused-import)
************* Module exe_recreate_data_tuning
addmo_examples/executables/exe_recreate_data_tuning.py:1:0: C0301: Line too long (122/100) (line-too-long)
addmo_examples/executables/exe_recreate_data_tuning.py:2:0: C0301: Line too long (137/100) (line-too-long)
addmo_examples/executables/exe_recreate_data_tuning.py:19:0: C0301: Line too long (115/100) (line-too-long)
addmo_examples/executables/exe_recreate_data_tuning.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo_examples/executables/exe_recreate_data_tuning.py:5:0: E0401: Unable to import 'pandas' (import-error)
addmo_examples/executables/exe_recreate_data_tuning.py:6:0: E0401: Unable to import 'addmo.util.definitions' (import-error)
addmo_examples/executables/exe_recreate_data_tuning.py:7:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
addmo_examples/executables/exe_recreate_data_tuning.py:8:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo_examples/executables/exe_recreate_data_tuning.py:9:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo_examples/executables/exe_recreate_data_tuning.py:10:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo_examples/executables/exe_recreate_data_tuning.py:11:0: E0401: Unable to import 'addmo.s1_data_tuning_auto.config.data_tuning_auto_config' (import-error)
addmo_examples/executables/exe_recreate_data_tuning.py:12:0: E0401: Unable to import 'addmo.s1_data_tuning_auto.data_tuner_auto' (import-error)
addmo_examples/executables/exe_recreate_data_tuning.py:14:20: W0621: Redefining name 'name_of_raw_data' from outer scope (line 59) (redefined-outer-name)
addmo_examples/executables/exe_recreate_data_tuning.py:14:38: W0621: Redefining name 'name_of_tuning' from outer scope (line 60) (redefined-outer-name)
addmo_examples/executables/exe_recreate_data_tuning.py:14:54: W0621: Redefining name 'abs_path_to_data' from outer scope (line 61) (redefined-outer-name)
addmo_examples/executables/exe_recreate_data_tuning.py:14:72: W0621: Redefining name 'name_new_config' from outer scope (line 62) (redefined-outer-name)
addmo_examples/executables/exe_recreate_data_tuning.py:21:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
addmo_examples/executables/exe_recreate_data_tuning.py:59:4: C0103: Constant name "name_of_raw_data" doesn't conform to UPPER_CASE naming style (invalid-name)
addmo_examples/executables/exe_recreate_data_tuning.py:60:4: C0103: Constant name "name_of_tuning" doesn't conform to UPPER_CASE naming style (invalid-name)
addmo_examples/executables/exe_recreate_data_tuning.py:62:4: C0103: Constant name "name_new_config" doesn't conform to UPPER_CASE naming style (invalid-name)
************* Module exe_data_tuning_fixed
addmo_examples/executables/exe_data_tuning_fixed.py:99:0: C0301: Line too long (166/100) (line-too-long)
addmo_examples/executables/exe_data_tuning_fixed.py:101:0: C0304: Final newline missing (missing-final-newline)
addmo_examples/executables/exe_data_tuning_fixed.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo_examples/executables/exe_data_tuning_fixed.py:3:0: E0401: Unable to import 'pandas' (import-error)
addmo_examples/executables/exe_data_tuning_fixed.py:4:0: E0401: Unable to import 'addmo.util.definitions' (import-error)
addmo_examples/executables/exe_data_tuning_fixed.py:5:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
addmo_examples/executables/exe_data_tuning_fixed.py:6:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo_examples/executables/exe_data_tuning_fixed.py:7:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo_examples/executables/exe_data_tuning_fixed.py:8:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo_examples/executables/exe_data_tuning_fixed.py:9:0: E0401: Unable to import 'addmo.s2_data_tuning.config.data_tuning_config' (import-error)
addmo_examples/executables/exe_data_tuning_fixed.py:10:0: E0401: Unable to import 'addmo.s2_data_tuning.data_tuner_fixed' (import-error)
addmo_examples/executables/exe_data_tuning_fixed.py:11:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
addmo_examples/executables/exe_data_tuning_fixed.py:12:0: E0401: Unable to import 'addmo.util.plotting_utils' (import-error)
addmo_examples/executables/exe_data_tuning_fixed.py:13:0: E0401: Unable to import 'addmo.util.data_handling' (import-error)
addmo_examples/executables/exe_data_tuning_fixed.py:14:0: E0401: Unable to import 'addmo.s5_insights.model_plots.time_series' (import-error)
addmo_examples/executables/exe_data_tuning_fixed.py:15:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
addmo_examples/executables/exe_data_tuning_fixed.py:17:0: R0914: Too many local variables (19/15) (too-many-locals)
addmo_examples/executables/exe_data_tuning_fixed.py:17:29: W0621: Redefining name 'user_input' from outer scope (line 99) (redefined-outer-name)
addmo_examples/executables/exe_data_tuning_fixed.py:43:4: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
addmo_examples/executables/exe_data_tuning_fixed.py:43:7: C0103: Variable name "y" doesn't conform to snake_case naming style (invalid-name)
addmo_examples/executables/exe_data_tuning_fixed.py:68:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
addmo_examples/executables/exe_data_tuning_fixed.py:68:35: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
addmo_examples/executables/exe_data_tuning_fixed.py:43:4: W0612: Unused variable 'x' (unused-variable)
addmo_examples/executables/exe_data_tuning_fixed.py:84:26: W0621: Redefining name 'user_input' from outer scope (line 99) (redefined-outer-name)
addmo_examples/executables/exe_data_tuning_fixed.py:93:38: W0621: Redefining name 'user_input' from outer scope (line 99) (redefined-outer-name)
************* Module test_abstractmodel
tests/test_abstractmodel.py:75:0: C0301: Line too long (104/100) (line-too-long)
tests/test_abstractmodel.py:88:0: C0301: Line too long (102/100) (line-too-long)
tests/test_abstractmodel.py:89:0: C0301: Line too long (106/100) (line-too-long)
tests/test_abstractmodel.py:95:0: C0305: Trailing newlines (trailing-newlines)
tests/test_abstractmodel.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/test_abstractmodel.py:4:0: E0401: Unable to import 'pandas' (import-error)
tests/test_abstractmodel.py:5:0: E0401: Unable to import 'numpy' (import-error)
tests/test_abstractmodel.py:6:0: E0401: Unable to import 'addmo.s3_model_tuning.models.abstract_model' (import-error)
tests/test_abstractmodel.py:7:0: E0401: Unable to import 'addmo.s3_model_tuning.models.keras_models' (import-error)
tests/test_abstractmodel.py:8:0: E0401: Unable to import 'addmo.s3_model_tuning.models.scikit_learn_models' (import-error)
tests/test_abstractmodel.py:9:0: E0401: Unable to import 'addmo.s3_model_tuning.models.abstract_model' (import-error)
tests/test_abstractmodel.py:10:0: E0401: Unable to import 'addmo.s3_model_tuning.models.model_factory' (import-error)
tests/test_abstractmodel.py:49:23: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
tests/test_abstractmodel.py:7:0: W0611: Unused BaseKerasModel imported from addmo.s3_model_tuning.models.keras_models (unused-import)
************* Module test_data_tuning
tests/test_data_tuning.py:25:0: C0301: Line too long (136/100) (line-too-long)
tests/test_data_tuning.py:79:0: C0304: Final newline missing (missing-final-newline)
tests/test_data_tuning.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/test_data_tuning.py:5:0: E0401: Unable to import 'pandas' (import-error)
tests/test_data_tuning.py:7:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
tests/test_data_tuning.py:8:0: E0401: Unable to import 'addmo.s1_data_tuning_auto.config.data_tuning_auto_config' (import-error)
tests/test_data_tuning.py:9:0: E0401: Unable to import 'addmo.s1_data_tuning_auto.data_tuner_auto' (import-error)
tests/test_data_tuning.py:10:0: E0401: Unable to import 'addmo.s2_data_tuning.config.data_tuning_config' (import-error)
tests/test_data_tuning.py:11:0: E0401: Unable to import 'addmo.s2_data_tuning.data_tuner_fixed' (import-error)
tests/test_data_tuning.py:12:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
tests/test_data_tuning.py:13:0: E0401: Unable to import 'addmo.util.data_handling' (import-error)
tests/test_data_tuning.py:35:8: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
tests/test_data_tuning.py:35:11: C0103: Variable name "y" doesn't conform to snake_case naming style (invalid-name)
tests/test_data_tuning.py:38:4: C0116: Missing function or method docstring (missing-function-docstring)
tests/test_data_tuning.py:43:21: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
tests/test_data_tuning.py:43:24: C0103: Variable name "y" doesn't conform to snake_case naming style (invalid-name)
tests/test_data_tuning.py:6:0: C0411: standard import "from unittest.mock import patch, MagicMock" should be placed before "import pandas as pd" (wrong-import-order)
tests/test_data_tuning.py:1:0: W0611: Unused import os (unused-import)
tests/test_data_tuning.py:4:0: W0611: Unused import tempfile (unused-import)
tests/test_data_tuning.py:6:0: W0611: Unused patch imported from unittest.mock (unused-import)
tests/test_data_tuning.py:6:0: W0611: Unused MagicMock imported from unittest.mock (unused-import)
tests/test_data_tuning.py:7:0: W0611: Unused ExperimentLogger imported from addmo.util.experiment_logger (unused-import)
tests/test_data_tuning.py:7:0: W0611: Unused LocalLogger imported from addmo.util.experiment_logger (unused-import)
tests/test_data_tuning.py:7:0: W0611: Unused WandbLogger imported from addmo.util.experiment_logger (unused-import)
************* Module test_model_tuning
tests/test_model_tuning.py:27:0: C0301: Line too long (102/100) (line-too-long)
tests/test_model_tuning.py:31:0: C0301: Line too long (104/100) (line-too-long)
tests/test_model_tuning.py:43:0: C0301: Line too long (108/100) (line-too-long)
tests/test_model_tuning.py:46:0: C0301: Line too long (131/100) (line-too-long)
tests/test_model_tuning.py:51:0: C0301: Line too long (127/100) (line-too-long)
tests/test_model_tuning.py:56:0: C0304: Final newline missing (missing-final-newline)
tests/test_model_tuning.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/test_model_tuning.py:2:0: E0401: Unable to import 'pandas' (import-error)
tests/test_model_tuning.py:3:0: E0401: Unable to import 'addmo.s3_model_tuning.models.model_factory' (import-error)
tests/test_model_tuning.py:4:0: E0401: Unable to import 'addmo.s3_model_tuning.config.model_tuning_config' (import-error)
tests/test_model_tuning.py:5:0: E0401: Unable to import 'addmo.s3_model_tuning.config.model_tuning_config' (import-error)
tests/test_model_tuning.py:6:0: E0401: Unable to import 'addmo.s3_model_tuning.model_tuner' (import-error)
tests/test_model_tuning.py:7:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
tests/test_model_tuning.py:8:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
tests/test_model_tuning.py:9:0: E0401: Unable to import 'addmo.util.data_handling' (import-error)
tests/test_model_tuning.py:19:4: C0116: Missing function or method docstring (missing-function-docstring)
tests/test_model_tuning.py:20:40: W0212: Access to a protected member _config_model_tuner of a client class (protected-access)
tests/test_model_tuning.py:5:0: W0611: Unused ModelTunerConfig imported from addmo.s3_model_tuning.config.model_tuning_config (unused-import)
tests/test_model_tuning.py:8:0: W0611: Unused load_config_from_json imported from addmo.util.load_save (unused-import)
************* Module test_config_loading
tests/test_config_loading.py:5:0: C0301: Line too long (107/100) (line-too-long)
tests/test_config_loading.py:13:0: C0301: Line too long (121/100) (line-too-long)
tests/test_config_loading.py:29:0: C0301: Line too long (129/100) (line-too-long)
tests/test_config_loading.py:73:0: C0301: Line too long (119/100) (line-too-long)
tests/test_config_loading.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/test_config_loading.py:2:0: E0401: Unable to import 'pydantic' (import-error)
tests/test_config_loading.py:3:0: E0401: Unable to import 'addmo.s1_data_tuning_auto.config.data_tuning_auto_config' (import-error)
tests/test_config_loading.py:4:0: E0401: Unable to import 'addmo.s2_data_tuning.config.data_tuning_config' (import-error)
tests/test_config_loading.py:5:0: E0401: Unable to import 'addmo.s3_model_tuning.config.model_tuning_config' (import-error)
tests/test_config_loading.py:17:12: C0103: Variable name "ConfigClass" doesn't conform to snake_case naming style (invalid-name)
tests/test_config_loading.py:31:12: C0103: Variable name "ConfigClass" doesn't conform to snake_case naming style (invalid-name)
tests/test_config_loading.py:46:12: C0103: Variable name "ConfigClass" doesn't conform to snake_case naming style (invalid-name)
tests/test_config_loading.py:61:12: C0103: Variable name "ConfigClass" doesn't conform to snake_case naming style (invalid-name)
************* Module E2E_test
tests/E2E_test.py:7:0: C0301: Line too long (103/100) (line-too-long)
tests/E2E_test.py:12:0: C0301: Line too long (106/100) (line-too-long)
tests/E2E_test.py:15:0: C0301: Line too long (172/100) (line-too-long)
tests/E2E_test.py:16:0: C0301: Line too long (178/100) (line-too-long)
tests/E2E_test.py:19:0: C0301: Line too long (113/100) (line-too-long)
tests/E2E_test.py:30:0: C0301: Line too long (127/100) (line-too-long)
tests/E2E_test.py:31:0: C0301: Line too long (136/100) (line-too-long)
tests/E2E_test.py:32:0: C0301: Line too long (104/100) (line-too-long)
tests/E2E_test.py:33:0: C0301: Line too long (101/100) (line-too-long)
tests/E2E_test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tests/E2E_test.py:1:0: C0103: Module name "E2E_test" doesn't conform to snake_case naming style (invalid-name)
tests/E2E_test.py:4:0: E0401: Unable to import 'pandas' (import-error)
tests/E2E_test.py:6:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
tests/E2E_test.py:7:0: E0401: Unable to import 'addmo.util.definitions' (import-error)
tests/E2E_test.py:8:0: E0401: Unable to import 'addmo_examples.executables.exe_data_tuning_fixed' (import-error)
tests/E2E_test.py:9:0: E0401: Unable to import 'addmo_examples.executables.exe_model_tuning' (import-error)
tests/E2E_test.py:10:0: E0401: Unable to import 'addmo_examples.executables.exe_data_insights' (import-error)
tests/E2E_test.py:11:0: E0401: Unable to import 'addmo.s2_data_tuning.config.data_tuning_config' (import-error)
tests/E2E_test.py:12:0: E0401: Unable to import 'addmo.s3_model_tuning.config.model_tuning_config' (import-error)
tests/E2E_test.py:13:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
tests/E2E_test.py:21:0: C0115: Missing class docstring (missing-class-docstring)
tests/E2E_test.py:35:4: C0116: Missing function or method docstring (missing-function-docstring)
tests/E2E_test.py:5:0: C0411: standard import "from pathlib import Path" should be placed before "import pandas as pd" (wrong-import-order)
tests/E2E_test.py:11:0: C0412: Imports from package addmo are not grouped (ungrouped-imports)
tests/E2E_test.py:5:0: W0611: Unused Path imported from pathlib (unused-import)
************* Module app
GUI/app.py:15:0: C0301: Line too long (198/100) (line-too-long)
GUI/app.py:16:0: C0301: Line too long (171/100) (line-too-long)
GUI/app.py:17:0: C0301: Line too long (114/100) (line-too-long)
GUI/app.py:224:0: C0301: Line too long (109/100) (line-too-long)
GUI/app.py:240:0: C0301: Line too long (110/100) (line-too-long)
GUI/app.py:244:0: C0301: Line too long (105/100) (line-too-long)
GUI/app.py:247:0: C0301: Line too long (166/100) (line-too-long)
GUI/app.py:255:0: C0301: Line too long (114/100) (line-too-long)
GUI/app.py:281:0: C0301: Line too long (126/100) (line-too-long)
GUI/app.py:282:0: C0301: Line too long (117/100) (line-too-long)
GUI/app.py:349:0: C0301: Line too long (116/100) (line-too-long)
GUI/app.py:363:0: C0301: Line too long (114/100) (line-too-long)
GUI/app.py:390:0: C0301: Line too long (110/100) (line-too-long)
GUI/app.py:391:0: C0301: Line too long (110/100) (line-too-long)
GUI/app.py:392:0: C0301: Line too long (111/100) (line-too-long)
GUI/app.py:401:0: C0301: Line too long (141/100) (line-too-long)
GUI/app.py:406:0: C0301: Line too long (113/100) (line-too-long)
GUI/app.py:408:0: C0301: Line too long (113/100) (line-too-long)
GUI/app.py:409:0: C0301: Line too long (119/100) (line-too-long)
GUI/app.py:410:0: C0301: Line too long (101/100) (line-too-long)
GUI/app.py:412:0: C0301: Line too long (105/100) (line-too-long)
GUI/app.py:414:0: C0301: Line too long (145/100) (line-too-long)
GUI/app.py:416:0: C0301: Line too long (108/100) (line-too-long)
GUI/app.py:419:0: C0301: Line too long (113/100) (line-too-long)
GUI/app.py:422:0: C0301: Line too long (118/100) (line-too-long)
GUI/app.py:427:0: C0301: Line too long (110/100) (line-too-long)
GUI/app.py:471:0: C0301: Line too long (116/100) (line-too-long)
GUI/app.py:509:0: C0301: Line too long (120/100) (line-too-long)
GUI/app.py:523:0: C0301: Line too long (118/100) (line-too-long)
GUI/app.py:550:0: C0301: Line too long (114/100) (line-too-long)
GUI/app.py:551:0: C0301: Line too long (114/100) (line-too-long)
GUI/app.py:552:0: C0301: Line too long (134/100) (line-too-long)
GUI/app.py:560:0: C0301: Line too long (145/100) (line-too-long)
GUI/app.py:565:0: C0301: Line too long (117/100) (line-too-long)
GUI/app.py:567:0: C0301: Line too long (117/100) (line-too-long)
GUI/app.py:568:0: C0301: Line too long (196/100) (line-too-long)
GUI/app.py:570:0: C0301: Line too long (109/100) (line-too-long)
GUI/app.py:572:0: C0301: Line too long (149/100) (line-too-long)
GUI/app.py:573:0: C0301: Line too long (212/100) (line-too-long)
GUI/app.py:575:0: C0301: Line too long (117/100) (line-too-long)
GUI/app.py:578:0: C0301: Line too long (133/100) (line-too-long)
GUI/app.py:580:0: C0301: Line too long (102/100) (line-too-long)
GUI/app.py:582:0: C0301: Line too long (114/100) (line-too-long)
GUI/app.py:588:0: C0301: Line too long (136/100) (line-too-long)
GUI/app.py:606:0: C0301: Line too long (116/100) (line-too-long)
GUI/app.py:613:0: C0301: Line too long (144/100) (line-too-long)
GUI/app.py:615:0: C0301: Line too long (159/100) (line-too-long)
GUI/app.py:616:0: C0301: Line too long (138/100) (line-too-long)
GUI/app.py:617:0: C0301: Line too long (145/100) (line-too-long)
GUI/app.py:619:0: C0301: Line too long (112/100) (line-too-long)
GUI/app.py:621:0: C0301: Line too long (103/100) (line-too-long)
GUI/app.py:669:0: C0301: Line too long (125/100) (line-too-long)
GUI/app.py:670:0: C0301: Line too long (128/100) (line-too-long)
GUI/app.py:673:0: C0301: Line too long (108/100) (line-too-long)
GUI/app.py:738:0: C0301: Line too long (106/100) (line-too-long)
GUI/app.py:759:0: C0301: Line too long (115/100) (line-too-long)
GUI/app.py:763:0: C0301: Line too long (116/100) (line-too-long)
GUI/app.py:775:0: C0301: Line too long (110/100) (line-too-long)
GUI/app.py:873:0: C0301: Line too long (106/100) (line-too-long)
GUI/app.py:888:0: C0301: Line too long (168/100) (line-too-long)
GUI/app.py:893:0: C0301: Line too long (154/100) (line-too-long)
GUI/app.py:910:0: C0301: Line too long (125/100) (line-too-long)
GUI/app.py:912:0: C0301: Line too long (132/100) (line-too-long)
GUI/app.py:937:0: C0301: Line too long (140/100) (line-too-long)
GUI/app.py:974:0: C0301: Line too long (131/100) (line-too-long)
GUI/app.py:986:0: C0301: Line too long (121/100) (line-too-long)
GUI/app.py:1038:0: C0304: Final newline missing (missing-final-newline)
GUI/app.py:1:0: C0302: Too many lines in module (1038/1000) (too-many-lines)
GUI/app.py:1:0: C0114: Missing module docstring (missing-module-docstring)
GUI/app.py:2:0: E0401: Unable to import 'streamlit' (import-error)
GUI/app.py:4:0: C0410: Multiple imports on one line (io, os, zipfile) (multiple-imports)
GUI/app.py:5:0: E0401: Unable to import 'streamlit_pydantic' (import-error)
GUI/app.py:6:0: E0401: Unable to import 'addmo.s1_data_tuning_auto.config.data_tuning_auto_config' (import-error)
GUI/app.py:7:0: E0401: Unable to import 'addmo_examples.executables.exe_data_tuning_auto' (import-error)
GUI/app.py:8:0: E0401: Unable to import 'addmo_examples.executables.exe_data_tuning_fixed' (import-error)
GUI/app.py:9:0: E0401: Unable to import 'addmo.s2_data_tuning.config.data_tuning_config' (import-error)
GUI/app.py:10:0: E0401: Unable to import 'addmo.s3_model_tuning.config.model_tuning_config' (import-error)
GUI/app.py:11:0: E0401: Unable to import 'addmo_examples.executables.exe_model_tuning' (import-error)
GUI/app.py:12:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
GUI/app.py:13:0: E0401: Unable to import 'addmo.s3_model_tuning.config.model_tuning_config' (import-error)
GUI/app.py:14:0: E0401: Unable to import 'streamlit_pdf_viewer' (import-error)
GUI/app.py:15:0: E0401: Unable to import 'addmo.util.definitions' (import-error)
GUI/app.py:16:0: E0401: Unable to import 'addmo_examples.executables.exe_data_insights' (import-error)
GUI/app.py:17:0: E0401: Unable to import 'addmo.s4_model_testing.model_testing' (import-error)
GUI/app.py:18:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
GUI/app.py:22:72: C0103: Variable name "zf" doesn't conform to snake_case naming style (invalid-name)
GUI/app.py:24:16: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
GUI/app.py:34:8: W0621: Redefining name 'key' from outer scope (line 1000) (redefined-outer-name)
GUI/app.py:42:0: C0116: Missing function or method docstring (missing-function-docstring)
GUI/app.py:44:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
GUI/app.py:44:28: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
GUI/app.py:48:0: C0116: Missing function or method docstring (missing-function-docstring)
GUI/app.py:154:0: C0116: Missing function or method docstring (missing-function-docstring)
GUI/app.py:154:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
GUI/app.py:214:0: C0116: Missing function or method docstring (missing-function-docstring)
GUI/app.py:224:8: W0621: Redefining name 'key' from outer scope (line 1000) (redefined-outer-name)
GUI/app.py:214:0: R0915: Too many statements (56/50) (too-many-statements)
GUI/app.py:310:0: R0914: Too many local variables (18/15) (too-many-locals)
GUI/app.py:343:8: W0621: Redefining name 'submitted' from outer scope (line 987) (redefined-outer-name)
GUI/app.py:310:0: R0912: Too many branches (25/12) (too-many-branches)
GUI/app.py:310:0: R0915: Too many statements (88/50) (too-many-statements)
GUI/app.py:447:0: C0116: Missing function or method docstring (missing-function-docstring)
GUI/app.py:447:0: R0914: Too many local variables (24/15) (too-many-locals)
GUI/app.py:466:12: W0621: Redefining name 'submitted' from outer scope (line 987) (redefined-outer-name)
GUI/app.py:478:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
GUI/app.py:478:39: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
GUI/app.py:480:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
GUI/app.py:480:41: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
GUI/app.py:447:0: R0912: Too many branches (30/12) (too-many-branches)
GUI/app.py:447:0: R0915: Too many statements (111/50) (too-many-statements)
GUI/app.py:604:0: C0116: Missing function or method docstring (missing-function-docstring)
GUI/app.py:604:0: R0914: Too many local variables (17/15) (too-many-locals)
GUI/app.py:620:8: W0621: Redefining name 'submitted' from outer scope (line 987) (redefined-outer-name)
GUI/app.py:648:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
GUI/app.py:648:48: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
GUI/app.py:651:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
GUI/app.py:651:44: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
GUI/app.py:654:39: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
GUI/app.py:660:0: C0116: Missing function or method docstring (missing-function-docstring)
GUI/app.py:668:4: W0612: Unused variable 'choose_plotting_type' (unused-variable)
GUI/app.py:693:0: C0116: Missing function or method docstring (missing-function-docstring)
GUI/app.py:693:0: R0914: Too many local variables (16/15) (too-many-locals)
GUI/app.py:718:8: W0621: Redefining name 'key' from outer scope (line 1000) (redefined-outer-name)
GUI/app.py:739:12: W0621: Redefining name 'submitted' from outer scope (line 987) (redefined-outer-name)
GUI/app.py:775:16: W0621: Redefining name 'tuning_type' from outer scope (line 986) (redefined-outer-name)
GUI/app.py:754:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
GUI/app.py:754:39: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
GUI/app.py:693:0: R0912: Too many branches (28/12) (too-many-branches)
GUI/app.py:693:0: R0915: Too many statements (84/50) (too-many-statements)
GUI/app.py:845:0: C0116: Missing function or method docstring (missing-function-docstring)
GUI/app.py:872:12: W0621: Redefining name 'tuning_type' from outer scope (line 986) (redefined-outer-name)
GUI/app.py:878:12: W0621: Redefining name 'submitted' from outer scope (line 987) (redefined-outer-name)
GUI/app.py:904:17: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
GUI/app.py:904:43: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
GUI/app.py:910:29: W0612: Unused variable 'y_new' (unused-variable)
GUI/app.py:910:36: W0612: Unused variable 'new_config' (unused-variable)
GUI/app.py:912:29: W0612: Unused variable 'tuned_y_new' (unused-variable)
GUI/app.py:937:58: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
GUI/app.py:3:0: C0411: standard import "import json" should be placed before "import streamlit as st" (wrong-import-order)
GUI/app.py:4:0: C0411: standard import "import io, os, zipfile" should be placed before "import streamlit as st" (wrong-import-order)
GUI/app.py:4:0: C0411: standard import "import io, os, zipfile" should be placed before "import streamlit as st" (wrong-import-order)
GUI/app.py:4:0: C0411: standard import "import io, os, zipfile" should be placed before "import streamlit as st" (wrong-import-order)
GUI/app.py:14:0: C0411: third party import "from streamlit_pdf_viewer import pdf_viewer" should be placed before "from addmo.s1_data_tuning_auto.config.data_tuning_auto_config import DataTuningAutoSetup" (wrong-import-order)
GUI/app.py:9:0: C0412: Imports from package addmo are not grouped (ungrouped-imports)
GUI/app.py:11:0: C0412: Imports from package addmo_examples are not grouped (ungrouped-imports)
GUI/app.py:12:0: C0412: Imports from package addmo are not grouped (ungrouped-imports)
GUI/app.py:15:0: C0412: Imports from package addmo are not grouped (ungrouped-imports)
GUI/app.py:16:0: C0412: Imports from package addmo_examples are not grouped (ungrouped-imports)
GUI/app.py:17:0: C0412: Imports from package addmo are not grouped (ungrouped-imports)
GUI/app.py:5:0: W0611: Unused pydantic_output imported from streamlit_pydantic (unused-import)
GUI/app.py:5:0: W0611: Unused pydantic_form imported from streamlit_pydantic (unused-import)
GUI/app.py:16:0: W0611: Unused exe_parallel_plot imported from addmo_examples.executables.exe_data_insights (unused-import)
GUI/app.py:18:0: W0611: Unused load_data imported from addmo.util.load_save (unused-import)
************* Module launch_GUI
GUI/launch_GUI.py:11:0: C0304: Final newline missing (missing-final-newline)
GUI/launch_GUI.py:1:0: C0114: Missing module docstring (missing-module-docstring)
GUI/launch_GUI.py:1:0: C0103: Module name "launch_GUI" doesn't conform to snake_case naming style (invalid-name)
GUI/launch_GUI.py:4:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
GUI/launch_GUI.py:6:0: C0116: Missing function or method docstring (missing-function-docstring)
GUI/launch_GUI.py:8:4: W1510: 'subprocess.run' used without explicitly defining the value for 'check'. (subprocess-run-check)
************* Module parallel_plots
addmo/s5_insights/model_plots/parallel_plots.py:94:0: C0304: Final newline missing (missing-final-newline)
addmo/s5_insights/model_plots/parallel_plots.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s5_insights/model_plots/parallel_plots.py:1:0: E0401: Unable to import 'numpy' (import-error)
addmo/s5_insights/model_plots/parallel_plots.py:2:0: E0401: Unable to import 'pandas' (import-error)
addmo/s5_insights/model_plots/parallel_plots.py:3:0: E0401: Unable to import 'plotly.express' (import-error)
addmo/s5_insights/model_plots/parallel_plots.py:4:0: E0401: Unable to import 'matplotlib.pyplot' (import-error)
addmo/s5_insights/model_plots/parallel_plots.py:5:0: E0401: Unable to import 'addmo.util' (import-error)
addmo/s5_insights/model_plots/parallel_plots.py:6:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
addmo/s5_insights/model_plots/parallel_plots.py:9:0: C0116: Missing function or method docstring (missing-function-docstring)
addmo/s5_insights/model_plots/parallel_plots.py:9:0: R0914: Too many local variables (25/15) (too-many-locals)
addmo/s5_insights/model_plots/parallel_plots.py:37:4: C0103: Variable name "zs" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/parallel_plots.py:49:11: C0103: Variable name "ax" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/parallel_plots.py:73:0: C0116: Missing function or method docstring (missing-function-docstring)
addmo/s5_insights/model_plots/parallel_plots.py:6:0: W0611: Unused load_data imported from addmo.util.load_save (unused-import)
************* Module carpet_plots
addmo/s5_insights/model_plots/carpet_plots.py:31:0: C0301: Line too long (135/100) (line-too-long)
addmo/s5_insights/model_plots/carpet_plots.py:72:0: C0301: Line too long (125/100) (line-too-long)
addmo/s5_insights/model_plots/carpet_plots.py:125:0: C0301: Line too long (101/100) (line-too-long)
addmo/s5_insights/model_plots/carpet_plots.py:126:0: C0301: Line too long (101/100) (line-too-long)
addmo/s5_insights/model_plots/carpet_plots.py:127:0: C0301: Line too long (101/100) (line-too-long)
addmo/s5_insights/model_plots/carpet_plots.py:128:0: C0301: Line too long (101/100) (line-too-long)
addmo/s5_insights/model_plots/carpet_plots.py:197:0: C0301: Line too long (161/100) (line-too-long)
addmo/s5_insights/model_plots/carpet_plots.py:210:0: C0301: Line too long (101/100) (line-too-long)
addmo/s5_insights/model_plots/carpet_plots.py:211:0: C0301: Line too long (121/100) (line-too-long)
addmo/s5_insights/model_plots/carpet_plots.py:216:0: C0301: Line too long (124/100) (line-too-long)
addmo/s5_insights/model_plots/carpet_plots.py:244:0: C0301: Line too long (125/100) (line-too-long)
addmo/s5_insights/model_plots/carpet_plots.py:286:0: C0301: Line too long (105/100) (line-too-long)
addmo/s5_insights/model_plots/carpet_plots.py:288:0: C0301: Line too long (106/100) (line-too-long)
addmo/s5_insights/model_plots/carpet_plots.py:314:0: C0301: Line too long (109/100) (line-too-long)
addmo/s5_insights/model_plots/carpet_plots.py:315:0: C0301: Line too long (108/100) (line-too-long)
addmo/s5_insights/model_plots/carpet_plots.py:278:9: W0511: TODO: use this colormap incase of no truncation and set the background to darker grey (fixme)
addmo/s5_insights/model_plots/carpet_plots.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s5_insights/model_plots/carpet_plots.py:1:0: E0401: Unable to import 'numpy' (import-error)
addmo/s5_insights/model_plots/carpet_plots.py:3:0: E0401: Unable to import 'pandas' (import-error)
addmo/s5_insights/model_plots/carpet_plots.py:4:0: E0401: Unable to import 'matplotlib.pyplot' (import-error)
addmo/s5_insights/model_plots/carpet_plots.py:5:0: E0401: Unable to import 'addmo.util' (import-error)
addmo/s5_insights/model_plots/carpet_plots.py:8:0: E0401: Unable to import 'addmo.util.definitions' (import-error)
addmo/s5_insights/model_plots/carpet_plots.py:9:0: E0401: Unable to import 'addmo.s3_model_tuning.models.model_factory' (import-error)
addmo/s5_insights/model_plots/carpet_plots.py:10:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
addmo/s5_insights/model_plots/carpet_plots.py:11:0: W0404: Reimport 'matplotlib.pyplot' (imported line 4) (reimported)
addmo/s5_insights/model_plots/carpet_plots.py:11:0: E0401: Unable to import 'matplotlib.pyplot' (import-error)
addmo/s5_insights/model_plots/carpet_plots.py:13:0: E0401: Unable to import 'mpl_toolkits.mplot3d' (import-error)
addmo/s5_insights/model_plots/carpet_plots.py:14:0: E0401: Unable to import 'matplotlib' (import-error)
addmo/s5_insights/model_plots/carpet_plots.py:15:0: E0401: Unable to import 'matplotlib.colors' (import-error)
addmo/s5_insights/model_plots/carpet_plots.py:16:0: E0401: Unable to import 'addmo.util.plotting_utils' (import-error)
addmo/s5_insights/model_plots/carpet_plots.py:16:0: W0401: Wildcard import addmo.util.plotting_utils (wildcard-import)
addmo/s5_insights/model_plots/carpet_plots.py:17:0: R0402: Use 'from matplotlib import colors' instead (consider-using-from-import)
addmo/s5_insights/model_plots/carpet_plots.py:17:0: E0401: Unable to import 'matplotlib.colors' (import-error)
addmo/s5_insights/model_plots/carpet_plots.py:19:0: E0401: Unable to import 'matplotlib' (import-error)
addmo/s5_insights/model_plots/carpet_plots.py:19:0: W0404: Reimport 'cm' (imported line 14) (reimported)
addmo/s5_insights/model_plots/carpet_plots.py:20:0: E0401: Unable to import 'matplotlib.colors' (import-error)
addmo/s5_insights/model_plots/carpet_plots.py:22:59: C0103: Argument name "n" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/carpet_plots.py:31:0: R0913: Too many arguments (7/5) (too-many-arguments)
addmo/s5_insights/model_plots/carpet_plots.py:31:0: R0914: Too many local variables (44/15) (too-many-locals)
addmo/s5_insights/model_plots/carpet_plots.py:72:10: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
addmo/s5_insights/model_plots/carpet_plots.py:89:8: C0103: Variable name "ax" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/carpet_plots.py:90:8: C0103: Variable name "X" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/carpet_plots.py:90:11: C0103: Variable name "Y" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/carpet_plots.py:100:19: C0121: Comparison 'defaults_dict == None' should be 'defaults_dict is None' (singleton-comparison)
addmo/s5_insights/model_plots/carpet_plots.py:105:8: C0103: Variable name "Z1" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/carpet_plots.py:111:12: C0103: Variable name "Z2" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/carpet_plots.py:117:12: C0103: Variable name "Z1_greater" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/carpet_plots.py:118:12: C0103: Variable name "Z1_smaller" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/carpet_plots.py:119:12: C0103: Variable name "Z2_greater" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/carpet_plots.py:120:12: C0103: Variable name "Z2_smaller" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/carpet_plots.py:31:0: R0912: Too many branches (18/12) (too-many-branches)
addmo/s5_insights/model_plots/carpet_plots.py:31:0: R0915: Too many statements (84/50) (too-many-statements)
addmo/s5_insights/model_plots/carpet_plots.py:125:12: W0612: Unused variable 'surf2_smaller' (unused-variable)
addmo/s5_insights/model_plots/carpet_plots.py:126:12: W0612: Unused variable 'surf1_smaller' (unused-variable)
addmo/s5_insights/model_plots/carpet_plots.py:127:12: W0612: Unused variable 'surf2_greater' (unused-variable)
addmo/s5_insights/model_plots/carpet_plots.py:128:12: W0612: Unused variable 'surf1_greater' (unused-variable)
addmo/s5_insights/model_plots/carpet_plots.py:197:0: C0116: Missing function or method docstring (missing-function-docstring)
addmo/s5_insights/model_plots/carpet_plots.py:197:0: R0913: Too many arguments (8/5) (too-many-arguments)
addmo/s5_insights/model_plots/carpet_plots.py:197:0: R0914: Too many local variables (57/15) (too-many-locals)
addmo/s5_insights/model_plots/carpet_plots.py:244:10: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
addmo/s5_insights/model_plots/carpet_plots.py:260:8: C0103: Variable name "ax" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/carpet_plots.py:261:8: C0103: Variable name "X" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/carpet_plots.py:261:11: C0103: Variable name "Y" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/carpet_plots.py:274:8: C0103: Variable name "Z1" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/carpet_plots.py:289:12: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/carpet_plots.py:197:0: R0912: Too many branches (21/12) (too-many-branches)
addmo/s5_insights/model_plots/carpet_plots.py:197:0: R0915: Too many statements (97/50) (too-many-statements)
addmo/s5_insights/model_plots/carpet_plots.py:2:0: C0411: standard import "import math" should be placed before "import numpy as np" (wrong-import-order)
addmo/s5_insights/model_plots/carpet_plots.py:6:0: C0411: standard import "from pathlib import Path" should be placed before "import numpy as np" (wrong-import-order)
addmo/s5_insights/model_plots/carpet_plots.py:11:0: C0411: third party import "import matplotlib.pyplot as plt" should be placed before "from addmo.util import plotting_utils as d" (wrong-import-order)
addmo/s5_insights/model_plots/carpet_plots.py:12:0: C0411: standard import "from itertools import product" should be placed before "import numpy as np" (wrong-import-order)
addmo/s5_insights/model_plots/carpet_plots.py:13:0: C0411: third party import "from mpl_toolkits.mplot3d import Axes3D" should be placed before "from addmo.util import plotting_utils as d" (wrong-import-order)
addmo/s5_insights/model_plots/carpet_plots.py:14:0: C0411: third party import "from matplotlib import cm" should be placed before "from addmo.util import plotting_utils as d" (wrong-import-order)
addmo/s5_insights/model_plots/carpet_plots.py:15:0: C0411: third party import "from matplotlib.colors import ListedColormap" should be placed before "from addmo.util import plotting_utils as d" (wrong-import-order)
addmo/s5_insights/model_plots/carpet_plots.py:17:0: C0411: third party import "import matplotlib.colors as colors" should be placed before "from addmo.util import plotting_utils as d" (wrong-import-order)
addmo/s5_insights/model_plots/carpet_plots.py:19:0: C0411: third party import "from matplotlib import cm" should be placed before "from addmo.util import plotting_utils as d" (wrong-import-order)
addmo/s5_insights/model_plots/carpet_plots.py:20:0: C0411: third party import "from matplotlib.colors import LinearSegmentedColormap" should be placed before "from addmo.util import plotting_utils as d" (wrong-import-order)
addmo/s5_insights/model_plots/carpet_plots.py:11:0: C0412: Imports from package matplotlib are not grouped (ungrouped-imports)
addmo/s5_insights/model_plots/carpet_plots.py:16:0: C0412: Imports from package addmo are not grouped (ungrouped-imports)
addmo/s5_insights/model_plots/carpet_plots.py:17:0: C0412: Imports from package matplotlib are not grouped (ungrouped-imports)
addmo/s5_insights/model_plots/carpet_plots.py:6:0: W0611: Unused Path imported from pathlib (unused-import)
addmo/s5_insights/model_plots/carpet_plots.py:8:0: W0611: Unused return_results_dir_model_tuning imported from addmo.util.definitions (unused-import)
addmo/s5_insights/model_plots/carpet_plots.py:8:0: W0611: Unused return_best_model imported from addmo.util.definitions (unused-import)
addmo/s5_insights/model_plots/carpet_plots.py:9:0: W0611: Unused ModelFactory imported from addmo.s3_model_tuning.models.model_factory (unused-import)
addmo/s5_insights/model_plots/carpet_plots.py:10:0: W0611: Unused load_data imported from addmo.util.load_save (unused-import)
addmo/s5_insights/model_plots/carpet_plots.py:12:0: W0611: Unused product imported from itertools (unused-import)
addmo/s5_insights/model_plots/carpet_plots.py:13:0: W0611: Unused Axes3D imported from mpl_toolkits.mplot3d (unused-import)
addmo/s5_insights/model_plots/carpet_plots.py:15:0: W0611: Unused ListedColormap imported from matplotlib.colors (unused-import)
************* Module scatter_plot
addmo/s5_insights/model_plots/scatter_plot.py:12:0: C0301: Line too long (103/100) (line-too-long)
addmo/s5_insights/model_plots/scatter_plot.py:13:0: C0301: Line too long (180/100) (line-too-long)
addmo/s5_insights/model_plots/scatter_plot.py:20:0: C0304: Final newline missing (missing-final-newline)
addmo/s5_insights/model_plots/scatter_plot.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s5_insights/model_plots/scatter_plot.py:1:0: E0401: Unable to import 'matplotlib.pyplot' (import-error)
addmo/s5_insights/model_plots/scatter_plot.py:2:0: E0401: Unable to import 'addmo.util' (import-error)
addmo/s5_insights/model_plots/scatter_plot.py:5:0: C0116: Missing function or method docstring (missing-function-docstring)
addmo/s5_insights/model_plots/scatter_plot.py:13:127: R1735: Consider using '{"facecolor": 'white', "alpha": 0.7, "edgecolor": d.black}' instead of a call to 'dict'. (use-dict-literal)
************* Module plot_carpets_modelA
addmo/s5_insights/model_plots/plot_carpets_modelA.py:12:0: C0301: Line too long (115/100) (line-too-long)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:86:0: C0301: Line too long (101/100) (line-too-long)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:87:0: C0301: Line too long (101/100) (line-too-long)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:88:0: C0301: Line too long (101/100) (line-too-long)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:89:0: C0301: Line too long (101/100) (line-too-long)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:200:0: C0301: Line too long (154/100) (line-too-long)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:206:0: C0305: Trailing newlines (trailing-newlines)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:1:0: C0103: Module name "plot_carpets_modelA" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:202:4: W0622: Redefining built-in 'dir' (redefined-builtin)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:3:0: E0401: Unable to import 'pandas' (import-error)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:4:0: E0401: Unable to import 'numpy' (import-error)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:5:0: E0401: Unable to import 'matplotlib.pyplot' (import-error)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:6:0: R0402: Use 'from matplotlib import colors' instead (consider-using-from-import)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:6:0: E0401: Unable to import 'matplotlib.colors' (import-error)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:7:0: E0401: Unable to import 'utilities' (import-error)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:8:0: E0401: Unable to import 'addmo.s3_model_tuning.models.model_factory' (import-error)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:9:0: E0401: Unable to import 'aixtra.system_simulations' (import-error)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:12:0: R0914: Too many local variables (39/15) (too-many-locals)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:33:4: C0103: Variable name "gs" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:49:8: C0103: Variable name "ax" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:51:8: C0103: Variable name "X" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:51:11: C0103: Variable name "Y" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:61:19: C0121: Comparison 'defaults_dict == None' should be 'defaults_dict is None' (singleton-comparison)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:66:8: C0103: Variable name "Z1" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:72:12: C0103: Variable name "Z2" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:78:12: C0103: Variable name "Z1_greater" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:79:12: C0103: Variable name "Z1_smaller" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:80:12: C0103: Variable name "Z2_greater" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:81:12: C0103: Variable name "Z2_smaller" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:12:0: R0915: Too many statements (65/50) (too-many-statements)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:86:12: W0612: Unused variable 'surf2_smaller' (unused-variable)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:87:12: W0612: Unused variable 'surf1_smaller' (unused-variable)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:88:12: W0612: Unused variable 'surf2_greater' (unused-variable)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:89:12: W0612: Unused variable 'surf1_greater' (unused-variable)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:156:0: C0116: Missing function or method docstring (missing-function-docstring)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:156:12: W0621: Redefining name 'plot_name' from outer scope (line 197) (redefined-outer-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:156:23: W0621: Redefining name 'plot_dir' from outer scope (line 198) (redefined-outer-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:156:33: W0621: Redefining name 'path_to_regressor' from outer scope (line 204) (redefined-outer-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:181:4: W0621: Redefining name 'plt' from outer scope (line 5) (redefined-outer-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:197:4: C0103: Constant name "plot_name" doesn't conform to UPPER_CASE naming style (invalid-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:200:4: C0103: Constant name "pre_dir" doesn't conform to UPPER_CASE naming style (invalid-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:201:4: C0103: Constant name "pre_dir_2" doesn't conform to UPPER_CASE naming style (invalid-name)
addmo/s5_insights/model_plots/plot_carpets_modelA.py:9:0: C0411: third party import "from aixtra.system_simulations import system_simulations as sys_sim" should be placed before "from addmo.s3_model_tuning.models.model_factory import ModelFactory" (wrong-import-order)
************* Module time_series
addmo/s5_insights/model_plots/time_series.py:61:0: C0301: Line too long (102/100) (line-too-long)
addmo/s5_insights/model_plots/time_series.py:83:0: C0305: Trailing newlines (trailing-newlines)
addmo/s5_insights/model_plots/time_series.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s5_insights/model_plots/time_series.py:1:0: E0401: Unable to import 'pandas' (import-error)
addmo/s5_insights/model_plots/time_series.py:2:0: E0401: Unable to import 'matplotlib.dates' (import-error)
addmo/s5_insights/model_plots/time_series.py:3:0: E0401: Unable to import 'matplotlib.pyplot' (import-error)
addmo/s5_insights/model_plots/time_series.py:4:0: E0401: Unable to import 'addmo.util' (import-error)
addmo/s5_insights/model_plots/time_series.py:5:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
addmo/s5_insights/model_plots/time_series.py:8:0: R0914: Too many local variables (19/15) (too-many-locals)
addmo/s5_insights/model_plots/time_series.py:35:8: C0103: Variable name "ax" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/time_series.py:64:12: C0103: Variable name "ax" doesn't conform to snake_case naming style (invalid-name)
addmo/s5_insights/model_plots/time_series.py:5:0: W0611: Unused load_data imported from addmo.util.load_save (unused-import)
************* Module feature_constructor
addmo/s2_data_tuning/feature_constructor.py:28:0: C0304: Final newline missing (missing-final-newline)
addmo/s2_data_tuning/feature_constructor.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s2_data_tuning/feature_constructor.py:1:0: E0401: Unable to import 'pandas' (import-error)
addmo/s2_data_tuning/feature_constructor.py:3:0: W0105: String statement has no effect (pointless-string-statement)
************* Module data_tuner_fixed
addmo/s2_data_tuning/data_tuner_fixed.py:61:0: C0304: Final newline missing (missing-final-newline)
addmo/s2_data_tuning/data_tuner_fixed.py:30:49: W0511: Todo: notwenig? (fixme)
addmo/s2_data_tuning/data_tuner_fixed.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s2_data_tuning/data_tuner_fixed.py:1:0: E0401: Unable to import 'pandas' (import-error)
addmo/s2_data_tuning/data_tuner_fixed.py:3:0: E0401: Unable to import 'addmo.s2_data_tuning.config.data_tuning_config' (import-error)
addmo/s2_data_tuning/data_tuner_fixed.py:4:0: E0401: Unable to import 'addmo.s2_data_tuning' (import-error)
addmo/s2_data_tuning/data_tuner_fixed.py:5:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
addmo/s2_data_tuning/data_tuner_fixed.py:6:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo/s2_data_tuning/data_tuner_fixed.py:36:4: C0116: Missing function or method docstring (missing-function-docstring)
addmo/s2_data_tuning/data_tuner_fixed.py:25:8: W0201: Attribute 'xy_raw' defined outside __init__ (attribute-defined-outside-init)
addmo/s2_data_tuning/data_tuner_fixed.py:28:8: W0201: Attribute 'xy_raw' defined outside __init__ (attribute-defined-outside-init)
addmo/s2_data_tuning/data_tuner_fixed.py:33:8: W0201: Attribute 'xy_raw' defined outside __init__ (attribute-defined-outside-init)
addmo/s2_data_tuning/data_tuner_fixed.py:5:0: W0611: Unused load_data imported from addmo.util.load_save (unused-import)
addmo/s2_data_tuning/data_tuner_fixed.py:6:0: W0611: Unused ExperimentLogger imported from addmo.util.experiment_logger (unused-import)
************* Module data_tuning_config
addmo/s2_data_tuning/config/data_tuning_config.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s2_data_tuning/config/data_tuning_config.py:2:0: E0401: Unable to import 'pydantic' (import-error)
addmo/s2_data_tuning/config/data_tuning_config.py:3:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
addmo/s2_data_tuning/config/data_tuning_config.py:4:0: E0401: Unable to import 'pydantic' (import-error)
addmo/s2_data_tuning/config/data_tuning_config.py:6:0: C0115: Missing class docstring (missing-class-docstring)
addmo/s2_data_tuning/config/data_tuning_config.py:6:0: R0903: Too few public methods (0/2) (too-few-public-methods)
addmo/s2_data_tuning/config/data_tuning_config.py:4:0: C0411: third party import "from pydantic import conlist" should be placed before "from addmo.util.load_save_utils import root_dir" (wrong-import-order)
addmo/s2_data_tuning/config/data_tuning_config.py:4:0: C0412: Imports from package pydantic are not grouped (ungrouped-imports)
addmo/s2_data_tuning/config/data_tuning_config.py:4:0: W0611: Unused conlist imported from pydantic (unused-import)
************* Module model_tuner
addmo/s3_model_tuning/model_tuner.py:79:0: C0305: Trailing newlines (trailing-newlines)
addmo/s3_model_tuning/model_tuner.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s3_model_tuning/model_tuner.py:3:0: E0401: Unable to import 'sklearn.metrics' (import-error)
addmo/s3_model_tuning/model_tuner.py:5:0: E0401: Unable to import 'addmo.s3_model_tuning.config.model_tuning_config' (import-error)
addmo/s3_model_tuning/model_tuner.py:6:0: E0401: Unable to import 'addmo.s3_model_tuning.models.model_factory' (import-error)
addmo/s3_model_tuning/model_tuner.py:7:0: E0401: Unable to import 'addmo.s3_model_tuning.hyperparameter_tuning.hyparam_tuning_factory' (import-error)
addmo/s3_model_tuning/model_tuner.py:10:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.validator_factory' (import-error)
addmo/s3_model_tuning/model_tuner.py:13:0: C0115: Missing class docstring (missing-class-docstring)
************* Module hyperparameter_tuning.hyparam_tuning_factory
addmo/s3_model_tuning/hyperparameter_tuning/hyparam_tuning_factory.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s3_model_tuning/hyperparameter_tuning/hyparam_tuning_factory.py:1:0: E0401: Unable to import 'addmo.s3_model_tuning.hyperparameter_tuning.hyperparameter_tuner' (import-error)
addmo/s3_model_tuning/hyperparameter_tuning/hyparam_tuning_factory.py:6:0: E0401: Unable to import 'addmo.s3_model_tuning.models.abstract_model' (import-error)
addmo/s3_model_tuning/hyperparameter_tuning/hyparam_tuning_factory.py:7:0: E0401: Unable to import 'addmo.s3_model_tuning.config.model_tuning_config' (import-error)
addmo/s3_model_tuning/hyperparameter_tuning/hyparam_tuning_factory.py:8:0: E0401: Unable to import 'addmo.s3_model_tuning.hyperparameter_tuning.abstract_hyparam_tuner' (import-error)
addmo/s3_model_tuning/hyperparameter_tuning/hyparam_tuning_factory.py:11:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.abstract_scorer' (import-error)
addmo/s3_model_tuning/hyperparameter_tuning/hyparam_tuning_factory.py:30:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
addmo/s3_model_tuning/hyperparameter_tuning/hyparam_tuning_factory.py:37:29: C0209: Formatting a regular string which could be a f-string (consider-using-f-string)
addmo/s3_model_tuning/hyperparameter_tuning/hyparam_tuning_factory.py:14:0: R0903: Too few public methods (1/2) (too-few-public-methods)
addmo/s3_model_tuning/hyperparameter_tuning/hyparam_tuning_factory.py:6:0: W0611: Unused AbstractMLModel imported from addmo.s3_model_tuning.models.abstract_model (unused-import)
************* Module hyperparameter_tuning.abstract_hyparam_tuner
addmo/s3_model_tuning/hyperparameter_tuning/abstract_hyparam_tuner.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s3_model_tuning/hyperparameter_tuning/abstract_hyparam_tuner.py:2:0: E0401: Unable to import 'addmo.s3_model_tuning.models.abstract_model' (import-error)
addmo/s3_model_tuning/hyperparameter_tuning/abstract_hyparam_tuner.py:3:0: E0401: Unable to import 'addmo.s3_model_tuning.config.model_tuning_config' (import-error)
addmo/s3_model_tuning/hyperparameter_tuning/abstract_hyparam_tuner.py:4:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.abstract_scorer' (import-error)
addmo/s3_model_tuning/hyperparameter_tuning/abstract_hyparam_tuner.py:7:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module hyperparameter_tuning.hyperparameter_tuner
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:39:0: C0301: Line too long (111/100) (line-too-long)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:2:0: E0401: Unable to import 'optuna' (import-error)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:3:0: E0401: Unable to import 'wandb' (import-error)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:4:0: E0401: Unable to import 'sklearn.model_selection' (import-error)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:5:0: E0401: Unable to import 'addmo.s3_model_tuning.models.abstract_model' (import-error)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:6:0: E0401: Unable to import 'addmo.s3_model_tuning.hyperparameter_tuning.abstract_hyparam_tuner' (import-error)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:9:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:10:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:18:43: W0613: Unused argument 'x_train_val' (unused-argument)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:18:56: W0613: Unused argument 'y_train_val' (unused-argument)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:13:0: R0903: Too few public methods (1/2) (too-few-public-methods)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:31:0: C0115: Missing class docstring (missing-class-docstring)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:32:0: W0613: Unused argument 'kwargs' (unused-argument)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:31:0: R0903: Too few public methods (1/2) (too-few-public-methods)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:96:0: W0613: Unused argument 'kwargs' (unused-argument)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:91:0: R0903: Too few public methods (1/2) (too-few-public-methods)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:3:0: W0611: Unused import wandb (unused-import)
addmo/s3_model_tuning/hyperparameter_tuning/hyperparameter_tuner.py:10:0: W0611: Unused WandbLogger imported from addmo.util.experiment_logger (unused-import)
************* Module abstract_scorer
addmo/s3_model_tuning/scoring/abstract_scorer.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s3_model_tuning/scoring/abstract_scorer.py:3:0: E0401: Unable to import 'addmo.s3_model_tuning.config.model_tuning_config' (import-error)
addmo/s3_model_tuning/scoring/abstract_scorer.py:4:0: E0401: Unable to import 'addmo.s3_model_tuning.models.abstract_model' (import-error)
addmo/s3_model_tuning/scoring/abstract_scorer.py:5:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.metrics.abstract_metric' (import-error)
addmo/s3_model_tuning/scoring/abstract_scorer.py:6:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.metrics.metric_factory' (import-error)
addmo/s3_model_tuning/scoring/abstract_scorer.py:7:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.validation_splitting.splitter_factory' (import-error)
addmo/s3_model_tuning/scoring/abstract_scorer.py:20:49: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/abstract_scorer.py:20:52: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/abstract_scorer.py:12:0: R0903: Too few public methods (1/2) (too-few-public-methods)
addmo/s3_model_tuning/scoring/abstract_scorer.py:26:0: C0115: Missing class docstring (missing-class-docstring)
addmo/s3_model_tuning/scoring/abstract_scorer.py:35:49: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/abstract_scorer.py:35:52: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/abstract_scorer.py:39:8: W0107: Unnecessary pass statement (unnecessary-pass)
addmo/s3_model_tuning/scoring/abstract_scorer.py:26:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module validator
addmo/s3_model_tuning/scoring/validator.py:49:0: C0305: Trailing newlines (trailing-newlines)
addmo/s3_model_tuning/scoring/validator.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s3_model_tuning/scoring/validator.py:1:0: E0401: Unable to import 'numpy' (import-error)
addmo/s3_model_tuning/scoring/validator.py:2:0: E0401: Unable to import 'sklearn.model_selection' (import-error)
addmo/s3_model_tuning/scoring/validator.py:4:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.abstract_scorer' (import-error)
addmo/s3_model_tuning/scoring/validator.py:5:0: E0401: Unable to import 'addmo.s3_model_tuning.models.abstract_model' (import-error)
addmo/s3_model_tuning/scoring/validator.py:7:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo/s3_model_tuning/scoring/validator.py:9:0: C0115: Missing class docstring (missing-class-docstring)
addmo/s3_model_tuning/scoring/validator.py:13:55: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validator.py:13:58: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validator.py:13:31: W0613: Unused argument 'model' (unused-argument)
addmo/s3_model_tuning/scoring/validator.py:13:55: W0613: Unused argument 'x' (unused-argument)
addmo/s3_model_tuning/scoring/validator.py:13:58: W0613: Unused argument 'y' (unused-argument)
addmo/s3_model_tuning/scoring/validator.py:9:0: R0903: Too few public methods (1/2) (too-few-public-methods)
addmo/s3_model_tuning/scoring/validator.py:17:0: C0115: Missing class docstring (missing-class-docstring)
addmo/s3_model_tuning/scoring/validator.py:18:55: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validator.py:18:58: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validator.py:17:0: R0903: Too few public methods (1/2) (too-few-public-methods)
addmo/s3_model_tuning/scoring/validator.py:7:0: W0611: Unused WandbLogger imported from addmo.util.experiment_logger (unused-import)
************* Module validator_factory
addmo/s3_model_tuning/scoring/validator_factory.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s3_model_tuning/scoring/validator_factory.py:1:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.abstract_scorer' (import-error)
addmo/s3_model_tuning/scoring/validator_factory.py:2:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.validator' (import-error)
addmo/s3_model_tuning/scoring/validator_factory.py:3:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.validator' (import-error)
addmo/s3_model_tuning/scoring/validator_factory.py:4:0: E0401: Unable to import 'addmo.s3_model_tuning.config.model_tuning_config' (import-error)
addmo/s3_model_tuning/scoring/validator_factory.py:12:4: C0116: Missing function or method docstring (missing-function-docstring)
addmo/s3_model_tuning/scoring/validator_factory.py:12:4: C0103: Method name "ValidatorFactory" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validator_factory.py:15:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
addmo/s3_model_tuning/scoring/validator_factory.py:6:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module metrics.abstract_metric
addmo/s3_model_tuning/scoring/metrics/abstract_metric.py:10:0: C0115: Missing class docstring (missing-class-docstring)
addmo/s3_model_tuning/scoring/metrics/abstract_metric.py:10:0: R0903: Too few public methods (0/2) (too-few-public-methods)
************* Module metrics.metric_factory
addmo/s3_model_tuning/scoring/metrics/metric_factory.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s3_model_tuning/scoring/metrics/metric_factory.py:3:0: E0401: Unable to import 'sklearn' (import-error)
addmo/s3_model_tuning/scoring/metrics/metric_factory.py:5:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.metrics' (import-error)
addmo/s3_model_tuning/scoring/metrics/metric_factory.py:6:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.metrics.abstract_metric' (import-error)
addmo/s3_model_tuning/scoring/metrics/metric_factory.py:19:8: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
addmo/s3_model_tuning/scoring/metrics/metric_factory.py:38:20: W0212: Access to a protected member _score_func of a client class (protected-access)
addmo/s3_model_tuning/scoring/metrics/metric_factory.py:9:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module validation_splitting.abstract_splitter
addmo/s3_model_tuning/scoring/validation_splitting/abstract_splitter.py:27:0: C0301: Line too long (103/100) (line-too-long)
addmo/s3_model_tuning/scoring/validation_splitting/abstract_splitter.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s3_model_tuning/scoring/validation_splitting/abstract_splitter.py:1:0: E0401: Unable to import 'numpy' (import-error)
addmo/s3_model_tuning/scoring/validation_splitting/abstract_splitter.py:3:0: E0401: Unable to import 'pandas' (import-error)
addmo/s3_model_tuning/scoring/validation_splitting/abstract_splitter.py:5:0: E0401: Unable to import 'sklearn.model_selection' (import-error)
addmo/s3_model_tuning/scoring/validation_splitting/abstract_splitter.py:26:20: C0103: Argument name "X" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validation_splitting/abstract_splitter.py:26:44: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validation_splitting/abstract_splitter.py:45:27: C0103: Argument name "X" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validation_splitting/abstract_splitter.py:45:51: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validation_splitting/abstract_splitter.py:50:14: C0103: Argument name "X" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validation_splitting/abstract_splitter.py:50:38: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validation_splitting/abstract_splitter.py:62:14: C0103: Argument name "X" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validation_splitting/abstract_splitter.py:62:38: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
************* Module validation_splitting.custom_splitters
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:1:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.validation_splitting.abstract_splitter' (import-error)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:5:0: W0105: String statement has no effect (pointless-string-statement)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:21:27: C0103: Argument name "X" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:21:35: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:21:27: W0613: Unused argument 'X' (unused-argument)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:21:35: W0613: Unused argument 'y' (unused-argument)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:21:43: W0613: Unused argument 'groups' (unused-argument)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:25:33: C0103: Argument name "X" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:25:36: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:25:36: W0613: Unused argument 'y' (unused-argument)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:25:44: W0613: Unused argument 'groups' (unused-argument)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:9:0: R0903: Too few public methods (1/2) (too-few-public-methods)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:65:4: C0116: Missing function or method docstring (missing-function-docstring)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:65:27: C0103: Argument name "X" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:65:30: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:65:30: W0613: Unused argument 'y' (unused-argument)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:65:38: W0613: Unused argument 'groups' (unused-argument)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:70:33: C0103: Argument name "X" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:70:36: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:70:36: W0613: Unused argument 'y' (unused-argument)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:70:44: W0613: Unused argument 'groups' (unused-argument)
addmo/s3_model_tuning/scoring/validation_splitting/custom_splitters.py:43:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module validation_splitting.splitter_factory
addmo/s3_model_tuning/scoring/validation_splitting/splitter_factory.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s3_model_tuning/scoring/validation_splitting/splitter_factory.py:3:0: E0401: Unable to import 'sklearn' (import-error)
addmo/s3_model_tuning/scoring/validation_splitting/splitter_factory.py:5:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.validation_splitting' (import-error)
addmo/s3_model_tuning/scoring/validation_splitting/splitter_factory.py:6:0: E0401: Unable to import 'addmo.s3_model_tuning.config.model_tuning_config' (import-error)
addmo/s3_model_tuning/scoring/validation_splitting/splitter_factory.py:7:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.validation_splitting.abstract_splitter' (import-error)
addmo/s3_model_tuning/scoring/validation_splitting/splitter_factory.py:26:12: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
addmo/s3_model_tuning/scoring/validation_splitting/splitter_factory.py:36:12: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
addmo/s3_model_tuning/scoring/validation_splitting/splitter_factory.py:12:0: R0903: Too few public methods (1/2) (too-few-public-methods)
************* Module config.model_tuning_config
addmo/s3_model_tuning/config/model_tuning_config.py:11:0: C0301: Line too long (209/100) (line-too-long)
addmo/s3_model_tuning/config/model_tuning_config.py:64:0: C0301: Line too long (124/100) (line-too-long)
addmo/s3_model_tuning/config/model_tuning_config.py:92:0: C0305: Trailing newlines (trailing-newlines)
addmo/s3_model_tuning/config/model_tuning_config.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s3_model_tuning/config/model_tuning_config.py:2:0: E0401: Unable to import 'pydantic' (import-error)
addmo/s3_model_tuning/config/model_tuning_config.py:4:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
addmo/s3_model_tuning/config/model_tuning_config.py:7:0: C0115: Missing class docstring (missing-class-docstring)
addmo/s3_model_tuning/config/model_tuning_config.py:7:0: R0903: Too few public methods (0/2) (too-few-public-methods)
addmo/s3_model_tuning/config/model_tuning_config.py:54:0: C0115: Missing class docstring (missing-class-docstring)
addmo/s3_model_tuning/config/model_tuning_config.py:54:0: R0903: Too few public methods (0/2) (too-few-public-methods)
addmo/s3_model_tuning/config/model_tuning_config.py:3:0: C0411: standard import "from typing import Optional" should be placed before "from pydantic import BaseModel, Field, PrivateAttr" (wrong-import-order)
************* Module keras_models
addmo/s3_model_tuning/models/keras_models.py:108:0: C0301: Line too long (110/100) (line-too-long)
addmo/s3_model_tuning/models/keras_models.py:109:0: C0301: Line too long (109/100) (line-too-long)
addmo/s3_model_tuning/models/keras_models.py:144:0: C0301: Line too long (103/100) (line-too-long)
addmo/s3_model_tuning/models/keras_models.py:157:0: C0301: Line too long (116/100) (line-too-long)
addmo/s3_model_tuning/models/keras_models.py:192:0: C0301: Line too long (103/100) (line-too-long)
addmo/s3_model_tuning/models/keras_models.py:204:0: C0301: Line too long (118/100) (line-too-long)
addmo/s3_model_tuning/models/keras_models.py:206:0: C0301: Line too long (117/100) (line-too-long)
addmo/s3_model_tuning/models/keras_models.py:211:0: C0301: Line too long (109/100) (line-too-long)
addmo/s3_model_tuning/models/keras_models.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s3_model_tuning/models/keras_models.py:1:0: E0401: Unable to import 'keras' (import-error)
addmo/s3_model_tuning/models/keras_models.py:2:0: E0401: Unable to import 'tensorflow' (import-error)
addmo/s3_model_tuning/models/keras_models.py:3:0: E0401: Unable to import 'onnx' (import-error)
addmo/s3_model_tuning/models/keras_models.py:4:0: E0401: Unable to import 'numpy' (import-error)
addmo/s3_model_tuning/models/keras_models.py:8:0: E0401: Unable to import 'keras.src.models.sequential' (import-error)
addmo/s3_model_tuning/models/keras_models.py:9:0: E0401: Unable to import 'keras.src.layers' (import-error)
addmo/s3_model_tuning/models/keras_models.py:10:0: E0401: Unable to import 'keras.src.losses' (import-error)
addmo/s3_model_tuning/models/keras_models.py:11:0: E0401: Unable to import 'keras.src.callbacks' (import-error)
addmo/s3_model_tuning/models/keras_models.py:12:0: E0401: Unable to import 'scikeras.wrappers' (import-error)
addmo/s3_model_tuning/models/keras_models.py:13:0: E0401: Unable to import 'addmo.s3_model_tuning.models.abstract_model' (import-error)
addmo/s3_model_tuning/models/keras_models.py:14:0: E0401: Unable to import 'addmo.s3_model_tuning.models.abstract_model' (import-error)
addmo/s3_model_tuning/models/keras_models.py:15:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
addmo/s3_model_tuning/models/keras_models.py:27:8: W0201: Attribute 'metadata' defined outside __init__ (attribute-defined-outside-init)
addmo/s3_model_tuning/models/keras_models.py:18:0: R0903: Too few public methods (0/2) (too-few-public-methods)
addmo/s3_model_tuning/models/keras_models.py:45:18: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/keras_models.py:45:21: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/keras_models.py:54:22: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/keras_models.py:103:16: C0415: Import outside toplevel (tf2onnx) (import-outside-toplevel)
addmo/s3_model_tuning/models/keras_models.py:105:16: W0707: Consider explicitly re-raising using 'except ImportError as exc' and 'raise ImportError('tf2onnx is required to save the model in ONNX format') from exc' (raise-missing-from)
addmo/s3_model_tuning/models/keras_models.py:113:29: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
addmo/s3_model_tuning/models/keras_models.py:128:8: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/keras_models.py:129:8: C0103: Variable name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/keras_models.py:149:31: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/keras_models.py:166:30: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/keras_models.py:49:8: W0201: Attribute 'x_fit' defined outside __init__ (attribute-defined-outside-init)
addmo/s3_model_tuning/models/keras_models.py:50:8: W0201: Attribute 'y_fit' defined outside __init__ (attribute-defined-outside-init)
addmo/s3_model_tuning/models/keras_models.py:5:0: C0411: standard import "from abc import ABC" should be placed before "import keras" (wrong-import-order)
addmo/s3_model_tuning/models/keras_models.py:9:0: W0611: Unused Normalization imported from keras.src.layers (unused-import)
addmo/s3_model_tuning/models/keras_models.py:9:0: W0611: Unused Activation imported from keras.src.layers (unused-import)
************* Module abstract_model
addmo/s3_model_tuning/models/abstract_model.py:116:0: C0301: Line too long (104/100) (line-too-long)
addmo/s3_model_tuning/models/abstract_model.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s3_model_tuning/models/abstract_model.py:4:0: E0401: Unable to import 'onnxruntime' (import-error)
addmo/s3_model_tuning/models/abstract_model.py:5:0: E0401: Unable to import 'numpy' (import-error)
addmo/s3_model_tuning/models/abstract_model.py:8:0: E0401: Unable to import 'pandas' (import-error)
addmo/s3_model_tuning/models/abstract_model.py:9:0: E0401: Unable to import 'pydantic' (import-error)
addmo/s3_model_tuning/models/abstract_model.py:10:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
addmo/s3_model_tuning/models/abstract_model.py:13:0: R0903: Too few public methods (1/2) (too-few-public-methods)
addmo/s3_model_tuning/models/abstract_model.py:66:18: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/abstract_model.py:66:35: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/abstract_model.py:74:8: W0107: Unnecessary pass statement (unnecessary-pass)
addmo/s3_model_tuning/models/abstract_model.py:77:22: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/abstract_model.py:87:8: W0107: Unnecessary pass statement (unnecessary-pass)
addmo/s3_model_tuning/models/abstract_model.py:99:8: W0107: Unnecessary pass statement (unnecessary-pass)
addmo/s3_model_tuning/models/abstract_model.py:106:8: W0107: Unnecessary pass statement (unnecessary-pass)
addmo/s3_model_tuning/models/abstract_model.py:117:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
addmo/s3_model_tuning/models/abstract_model.py:117:41: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/abstract_model.py:118:22: E1101: Instance of 'AbstractMLModel' has no 'metadata' member (no-member)
addmo/s3_model_tuning/models/abstract_model.py:120:45: W0613: Unused argument 'input_shape' (unused-argument)
addmo/s3_model_tuning/models/abstract_model.py:131:30: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/abstract_model.py:144:8: W0107: Unnecessary pass statement (unnecessary-pass)
addmo/s3_model_tuning/models/abstract_model.py:154:8: W0107: Unnecessary pass statement (unnecessary-pass)
addmo/s3_model_tuning/models/abstract_model.py:164:8: W0107: Unnecessary pass statement (unnecessary-pass)
addmo/s3_model_tuning/models/abstract_model.py:177:8: W0107: Unnecessary pass statement (unnecessary-pass)
addmo/s3_model_tuning/models/abstract_model.py:187:8: W0107: Unnecessary pass statement (unnecessary-pass)
addmo/s3_model_tuning/models/abstract_model.py:197:8: W0107: Unnecessary pass statement (unnecessary-pass)
addmo/s3_model_tuning/models/abstract_model.py:209:4: W0221: Number of parameters was 3 in 'AbstractMLModel.load_regressor' and is now 2 in overriding 'PredictorOnnx.load_regressor' method (arguments-differ)
addmo/s3_model_tuning/models/abstract_model.py:215:8: C0103: Variable name "x_ONNX" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/abstract_model.py:219:22: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
addmo/s3_model_tuning/models/abstract_model.py:222:22: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
addmo/s3_model_tuning/models/abstract_model.py:225:22: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
addmo/s3_model_tuning/models/abstract_model.py:228:22: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
addmo/s3_model_tuning/models/abstract_model.py:231:22: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
addmo/s3_model_tuning/models/abstract_model.py:233:4: W0221: Number of parameters was 4 in 'AbstractMLModel.save_regressor' and is now 2 in overriding 'PredictorOnnx.save_regressor' method (arguments-differ)
addmo/s3_model_tuning/models/abstract_model.py:234:22: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
addmo/s3_model_tuning/models/abstract_model.py:233:29: W0613: Unused argument 'path' (unused-argument)
addmo/s3_model_tuning/models/abstract_model.py:237:22: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
addmo/s3_model_tuning/models/abstract_model.py:239:4: W0221: Number of parameters was 2 in 'AbstractMLModel.to_scikit_learn' and is now 1 in overriding 'PredictorOnnx.to_scikit_learn' method (arguments-differ)
addmo/s3_model_tuning/models/abstract_model.py:240:22: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
addmo/s3_model_tuning/models/abstract_model.py:243:22: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
addmo/s3_model_tuning/models/abstract_model.py:246:22: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
addmo/s3_model_tuning/models/abstract_model.py:245:30: W0613: Unused argument 'path' (unused-argument)
addmo/s3_model_tuning/models/abstract_model.py:245:36: W0613: Unused argument 'file_type' (unused-argument)
addmo/s3_model_tuning/models/abstract_model.py:248:4: C0116: Missing function or method docstring (missing-function-docstring)
addmo/s3_model_tuning/models/abstract_model.py:249:22: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
addmo/s3_model_tuning/models/abstract_model.py:6:0: C0411: standard import "import subprocess" should be placed before "import onnxruntime as rt" (wrong-import-order)
addmo/s3_model_tuning/models/abstract_model.py:7:0: C0411: standard import "from abc import ABC, abstractmethod" should be placed before "import onnxruntime as rt" (wrong-import-order)
addmo/s3_model_tuning/models/abstract_model.py:1:0: W0611: Unused import os (unused-import)
************* Module model_factory
addmo/s3_model_tuning/models/model_factory.py:32:0: W0311: Bad indentation. Found 13 spaces, expected 12 (bad-indentation)
addmo/s3_model_tuning/models/model_factory.py:33:0: W0311: Bad indentation. Found 13 spaces, expected 12 (bad-indentation)
addmo/s3_model_tuning/models/model_factory.py:44:0: C0301: Line too long (107/100) (line-too-long)
addmo/s3_model_tuning/models/model_factory.py:66:0: C0301: Line too long (175/100) (line-too-long)
addmo/s3_model_tuning/models/model_factory.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s3_model_tuning/models/model_factory.py:4:0: E0401: Unable to import 'joblib' (import-error)
addmo/s3_model_tuning/models/model_factory.py:6:0: E0401: Unable to import 'addmo.s3_model_tuning.models' (import-error)
addmo/s3_model_tuning/models/model_factory.py:7:0: E0401: Unable to import 'addmo.s3_model_tuning.models' (import-error)
addmo/s3_model_tuning/models/model_factory.py:8:0: E0401: Unable to import 'addmo.s3_model_tuning.models.abstract_model' (import-error)
addmo/s3_model_tuning/models/model_factory.py:9:0: E0401: Unable to import 'addmo.s3_model_tuning.models.abstract_model' (import-error)
addmo/s3_model_tuning/models/model_factory.py:10:0: E0401: Unable to import 'tensorflow' (import-error)
addmo/s3_model_tuning/models/model_factory.py:11:0: E0401: Unable to import 'tensorflow.keras.models' (import-error)
addmo/s3_model_tuning/models/model_factory.py:36:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
addmo/s3_model_tuning/models/model_factory.py:55:4: E0213: Method '_load_metadata' should have "self" as first argument (no-self-argument)
addmo/s3_model_tuning/models/model_factory.py:61:8: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
addmo/s3_model_tuning/models/model_factory.py:62:17: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
addmo/s3_model_tuning/models/model_factory.py:62:40: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/model_factory.py:5:0: C0411: standard import "import os" should be placed before "import joblib" (wrong-import-order)
addmo/s3_model_tuning/models/model_factory.py:10:0: C0411: third party import "from tensorflow import keras" should be placed before "from addmo.s3_model_tuning.models import scikit_learn_models" (wrong-import-order)
addmo/s3_model_tuning/models/model_factory.py:11:0: C0411: third party import "from tensorflow.keras.models import load_model" should be placed before "from addmo.s3_model_tuning.models import scikit_learn_models" (wrong-import-order)
addmo/s3_model_tuning/models/model_factory.py:2:0: W0611: Unused import sys (unused-import)
addmo/s3_model_tuning/models/model_factory.py:11:0: W0611: Unused load_model imported from tensorflow.keras.models (unused-import)
************* Module scikit_learn_models
addmo/s3_model_tuning/models/scikit_learn_models.py:24:0: C0301: Line too long (102/100) (line-too-long)
addmo/s3_model_tuning/models/scikit_learn_models.py:34:0: C0301: Line too long (102/100) (line-too-long)
addmo/s3_model_tuning/models/scikit_learn_models.py:82:0: C0301: Line too long (101/100) (line-too-long)
addmo/s3_model_tuning/models/scikit_learn_models.py:102:0: C0301: Line too long (105/100) (line-too-long)
addmo/s3_model_tuning/models/scikit_learn_models.py:176:0: C0301: Line too long (106/100) (line-too-long)
addmo/s3_model_tuning/models/scikit_learn_models.py:286:0: C0301: Line too long (107/100) (line-too-long)
addmo/s3_model_tuning/models/scikit_learn_models.py:287:0: C0301: Line too long (109/100) (line-too-long)
addmo/s3_model_tuning/models/scikit_learn_models.py:327:0: C0304: Final newline missing (missing-final-newline)
addmo/s3_model_tuning/models/scikit_learn_models.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s3_model_tuning/models/scikit_learn_models.py:1:0: E0401: Unable to import 'numpy' (import-error)
addmo/s3_model_tuning/models/scikit_learn_models.py:2:0: E0401: Unable to import 'joblib' (import-error)
addmo/s3_model_tuning/models/scikit_learn_models.py:3:0: E0401: Unable to import 'sklearn' (import-error)
addmo/s3_model_tuning/models/scikit_learn_models.py:5:0: E0401: Unable to import 'sklearn.neural_network' (import-error)
addmo/s3_model_tuning/models/scikit_learn_models.py:6:0: E0401: Unable to import 'sklearn.svm' (import-error)
addmo/s3_model_tuning/models/scikit_learn_models.py:7:0: E0401: Unable to import 'sklearn.pipeline' (import-error)
addmo/s3_model_tuning/models/scikit_learn_models.py:8:0: E0401: Unable to import 'sklearn.preprocessing' (import-error)
addmo/s3_model_tuning/models/scikit_learn_models.py:9:0: E0401: Unable to import 'sklearn.compose' (import-error)
addmo/s3_model_tuning/models/scikit_learn_models.py:10:0: E0401: Unable to import 'skl2onnx' (import-error)
addmo/s3_model_tuning/models/scikit_learn_models.py:11:0: E0401: Unable to import 'addmo.s3_model_tuning.models.abstract_model' (import-error)
addmo/s3_model_tuning/models/scikit_learn_models.py:12:0: E0401: Unable to import 'addmo.s3_model_tuning.models.abstract_model' (import-error)
addmo/s3_model_tuning/models/scikit_learn_models.py:13:0: E0401: Unable to import 'sklearn.linear_model' (import-error)
addmo/s3_model_tuning/models/scikit_learn_models.py:14:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
addmo/s3_model_tuning/models/scikit_learn_models.py:39:18: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/scikit_learn_models.py:39:21: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/scikit_learn_models.py:47:22: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/scikit_learn_models.py:79:37: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/scikit_learn_models.py:82:29: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
addmo/s3_model_tuning/models/scikit_learn_models.py:97:4: C0116: Missing function or method docstring (missing-function-docstring)
addmo/s3_model_tuning/models/scikit_learn_models.py:97:30: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s3_model_tuning/models/scikit_learn_models.py:97:30: W0613: Unused argument 'x' (unused-argument)
addmo/s3_model_tuning/models/scikit_learn_models.py:43:8: W0201: Attribute 'x_fit' defined outside __init__ (attribute-defined-outside-init)
addmo/s3_model_tuning/models/scikit_learn_models.py:44:8: W0201: Attribute 'y_fit' defined outside __init__ (attribute-defined-outside-init)
addmo/s3_model_tuning/models/scikit_learn_models.py:57:8: W0201: Attribute 'metadata' defined outside __init__ (attribute-defined-outside-init)
addmo/s3_model_tuning/models/scikit_learn_models.py:159:0: C0115: Missing class docstring (missing-class-docstring)
addmo/s3_model_tuning/models/scikit_learn_models.py:159:0: C0103: Class name "ScikitMLP_TargetTransformed" doesn't conform to PascalCase naming style (invalid-name)
addmo/s3_model_tuning/models/scikit_learn_models.py:160:4: W0231: __init__ method from base class 'ScikitMLP' is not called (super-init-not-called)
addmo/s3_model_tuning/models/scikit_learn_models.py:193:4: C0116: Missing function or method docstring (missing-function-docstring)
addmo/s3_model_tuning/models/scikit_learn_models.py:196:4: C0116: Missing function or method docstring (missing-function-docstring)
addmo/s3_model_tuning/models/scikit_learn_models.py:205:0: C0115: Missing class docstring (missing-class-docstring)
addmo/s3_model_tuning/models/scikit_learn_models.py:206:4: W0231: __init__ method from base class 'ScikitLinearReg' is not called (super-init-not-called)
addmo/s3_model_tuning/models/scikit_learn_models.py:220:8: W0201: Attribute 'x_fit' defined outside __init__ (attribute-defined-outside-init)
addmo/s3_model_tuning/models/scikit_learn_models.py:221:8: W0201: Attribute 'y_fit' defined outside __init__ (attribute-defined-outside-init)
addmo/s3_model_tuning/models/scikit_learn_models.py:246:8: W0201: Attribute 'metadata' defined outside __init__ (attribute-defined-outside-init)
addmo/s3_model_tuning/models/scikit_learn_models.py:276:4: C0116: Missing function or method docstring (missing-function-docstring)
addmo/s3_model_tuning/models/scikit_learn_models.py:266:8: W0201: Attribute 'metadata' defined outside __init__ (attribute-defined-outside-init)
addmo/s3_model_tuning/models/scikit_learn_models.py:4:0: C0411: standard import "from abc import ABC" should be placed before "import numpy as np" (wrong-import-order)
addmo/s3_model_tuning/models/scikit_learn_models.py:13:0: C0411: third party import "from sklearn.linear_model import LinearRegression" should be placed before "from addmo.s3_model_tuning.models.abstract_model import AbstractMLModel" (wrong-import-order)
addmo/s3_model_tuning/models/scikit_learn_models.py:13:0: C0412: Imports from package sklearn are not grouped (ungrouped-imports)
addmo/s3_model_tuning/models/scikit_learn_models.py:14:0: C0412: Imports from package addmo are not grouped (ungrouped-imports)
addmo/s3_model_tuning/models/scikit_learn_models.py:8:0: W0611: Unused MaxAbsScaler imported from sklearn.preprocessing (unused-import)
************* Module data_tuner_auto
addmo/s1_data_tuning_auto/data_tuner_auto.py:56:0: C0305: Trailing newlines (trailing-newlines)
addmo/s1_data_tuning_auto/data_tuner_auto.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s1_data_tuning_auto/data_tuner_auto.py:1:0: E0401: Unable to import 'pandas' (import-error)
addmo/s1_data_tuning_auto/data_tuner_auto.py:2:0: E0401: Unable to import 'addmo.s1_data_tuning_auto.config.data_tuning_auto_config' (import-error)
addmo/s1_data_tuning_auto/data_tuner_auto.py:3:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
addmo/s1_data_tuning_auto/data_tuner_auto.py:4:0: E0401: Unable to import 'addmo.s1_data_tuning_auto' (import-error)
addmo/s1_data_tuning_auto/data_tuner_auto.py:5:0: E0401: Unable to import 'addmo.s1_data_tuning_auto' (import-error)
addmo/s1_data_tuning_auto/data_tuner_auto.py:6:0: E0401: Unable to import 'addmo.util.data_handling' (import-error)
addmo/s1_data_tuning_auto/data_tuner_auto.py:17:8: C0103: Attribute name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s1_data_tuning_auto/data_tuner_auto.py:17:16: C0103: Attribute name "y" doesn't conform to snake_case naming style (invalid-name)
************* Module feature_selection
addmo/s1_data_tuning_auto/feature_selection.py:69:0: C0301: Line too long (102/100) (line-too-long)
addmo/s1_data_tuning_auto/feature_selection.py:72:0: C0301: Line too long (121/100) (line-too-long)
addmo/s1_data_tuning_auto/feature_selection.py:140:0: C0304: Final newline missing (missing-final-newline)
addmo/s1_data_tuning_auto/feature_selection.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s1_data_tuning_auto/feature_selection.py:1:0: E0401: Unable to import 'pandas' (import-error)
addmo/s1_data_tuning_auto/feature_selection.py:2:0: E0401: Unable to import 'numpy' (import-error)
addmo/s1_data_tuning_auto/feature_selection.py:3:0: E0401: Unable to import 'sklearn.feature_selection' (import-error)
addmo/s1_data_tuning_auto/feature_selection.py:4:0: E0401: Unable to import 'sklearn.decomposition' (import-error)
addmo/s1_data_tuning_auto/feature_selection.py:5:0: E0401: Unable to import 'sklearn.feature_selection' (import-error)
addmo/s1_data_tuning_auto/feature_selection.py:6:0: E0401: Unable to import 'sklearn.feature_selection' (import-error)
addmo/s1_data_tuning_auto/feature_selection.py:7:0: E0401: Unable to import 'sklearn.ensemble' (import-error)
addmo/s1_data_tuning_auto/feature_selection.py:8:0: E0401: Unable to import 'sklearn.model_selection' (import-error)
addmo/s1_data_tuning_auto/feature_selection.py:9:0: E0401: Unable to import 'addmo.s1_data_tuning_auto.config.data_tuning_auto_config' (import-error)
addmo/s1_data_tuning_auto/feature_selection.py:12:55: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s1_data_tuning_auto/feature_selection.py:19:53: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s1_data_tuning_auto/feature_selection.py:24:4: W0622: Redefining built-in 'filter' (redefined-builtin)
addmo/s1_data_tuning_auto/feature_selection.py:31:15: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s1_data_tuning_auto/feature_selection.py:35:4: C0103: Variable name "Ica" doesn't conform to snake_case naming style (invalid-name)
addmo/s1_data_tuning_auto/feature_selection.py:41:51: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s1_data_tuning_auto/feature_selection.py:41:54: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s1_data_tuning_auto/feature_selection.py:70:70: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s1_data_tuning_auto/feature_selection.py:70:73: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s1_data_tuning_auto/feature_selection.py:98:70: C0103: Argument name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s1_data_tuning_auto/feature_selection.py:98:73: C0103: Argument name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s1_data_tuning_auto/feature_selection.py:98:0: R0914: Too many local variables (16/15) (too-many-locals)
************* Module feature_construction
addmo/s1_data_tuning_auto/feature_construction.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s1_data_tuning_auto/feature_construction.py:1:0: E0401: Unable to import 'pandas' (import-error)
addmo/s1_data_tuning_auto/feature_construction.py:3:0: E0401: Unable to import 'addmo.s2_data_tuning' (import-error)
addmo/s1_data_tuning_auto/feature_construction.py:4:0: E0401: Unable to import 'addmo.util.data_handling' (import-error)
addmo/s1_data_tuning_auto/feature_construction.py:5:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.validator_factory' (import-error)
addmo/s1_data_tuning_auto/feature_construction.py:6:0: E0401: Unable to import 'addmo.s3_model_tuning.models.model_factory' (import-error)
addmo/s1_data_tuning_auto/feature_construction.py:7:0: E0401: Unable to import 'addmo.s3_model_tuning.scoring.abstract_scorer' (import-error)
addmo/s1_data_tuning_auto/feature_construction.py:8:0: E0401: Unable to import 'addmo.s3_model_tuning.models.abstract_model' (import-error)
addmo/s1_data_tuning_auto/feature_construction.py:9:0: E0401: Unable to import 'addmo.s1_data_tuning_auto.config.data_tuning_auto_config' (import-error)
addmo/s1_data_tuning_auto/feature_construction.py:10:0: E0401: Unable to import 'addmo.s3_model_tuning.model_tuner' (import-error)
addmo/s1_data_tuning_auto/feature_construction.py:13:51: C0103: Argument name "xy" doesn't conform to snake_case naming style (invalid-name)
addmo/s1_data_tuning_auto/feature_construction.py:27:52: C0103: Argument name "xy" doesn't conform to snake_case naming style (invalid-name)
addmo/s1_data_tuning_auto/feature_construction.py:73:53: C0103: Argument name "xy" doesn't conform to snake_case naming style (invalid-name)
addmo/s1_data_tuning_auto/feature_construction.py:4:0: W0611: Unused split_target_features imported from addmo.util.data_handling (unused-import)
addmo/s1_data_tuning_auto/feature_construction.py:5:0: W0611: Unused ValidatorFactory imported from addmo.s3_model_tuning.scoring.validator_factory (unused-import)
addmo/s1_data_tuning_auto/feature_construction.py:6:0: W0611: Unused ModelFactory imported from addmo.s3_model_tuning.models.model_factory (unused-import)
addmo/s1_data_tuning_auto/feature_construction.py:7:0: W0611: Unused ValidationScoring imported from addmo.s3_model_tuning.scoring.abstract_scorer (unused-import)
addmo/s1_data_tuning_auto/feature_construction.py:8:0: W0611: Unused AbstractMLModel imported from addmo.s3_model_tuning.models.abstract_model (unused-import)
addmo/s1_data_tuning_auto/feature_construction.py:10:0: W0611: Unused ModelTuner imported from addmo.s3_model_tuning.model_tuner (unused-import)
************* Module config.data_tuning_auto_config
addmo/s1_data_tuning_auto/config/data_tuning_auto_config.py:74:0: C0305: Trailing newlines (trailing-newlines)
addmo/s1_data_tuning_auto/config/data_tuning_auto_config.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s1_data_tuning_auto/config/data_tuning_auto_config.py:2:0: E0401: Unable to import 'pydantic' (import-error)
addmo/s1_data_tuning_auto/config/data_tuning_auto_config.py:3:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
addmo/s1_data_tuning_auto/config/data_tuning_auto_config.py:5:0: C0115: Missing class docstring (missing-class-docstring)
addmo/s1_data_tuning_auto/config/data_tuning_auto_config.py:5:0: R0903: Too few public methods (0/2) (too-few-public-methods)
addmo/s1_data_tuning_auto/config/data_tuning_auto_config.py:2:0: W0611: Unused PrivateAttr imported from pydantic (unused-import)
************* Module model_testing
addmo/s4_model_testing/model_testing.py:9:0: C0301: Line too long (113/100) (line-too-long)
addmo/s4_model_testing/model_testing.py:30:0: C0301: Line too long (109/100) (line-too-long)
addmo/s4_model_testing/model_testing.py:35:0: C0301: Line too long (122/100) (line-too-long)
addmo/s4_model_testing/model_testing.py:46:0: C0301: Line too long (109/100) (line-too-long)
addmo/s4_model_testing/model_testing.py:51:0: C0301: Line too long (120/100) (line-too-long)
addmo/s4_model_testing/model_testing.py:67:0: C0301: Line too long (110/100) (line-too-long)
addmo/s4_model_testing/model_testing.py:148:0: C0305: Trailing newlines (trailing-newlines)
addmo/s4_model_testing/model_testing.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/s4_model_testing/model_testing.py:3:0: E0401: Unable to import 'pandas' (import-error)
addmo/s4_model_testing/model_testing.py:4:0: E0401: Unable to import 'addmo.util.definitions' (import-error)
addmo/s4_model_testing/model_testing.py:5:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
addmo/s4_model_testing/model_testing.py:6:0: E0401: Unable to import 'addmo.s1_data_tuning_auto.data_tuner_auto' (import-error)
addmo/s4_model_testing/model_testing.py:7:0: E0401: Unable to import 'addmo.s1_data_tuning_auto.config.data_tuning_auto_config' (import-error)
addmo/s4_model_testing/model_testing.py:8:0: E0401: Unable to import 'addmo.util.experiment_logger' (import-error)
addmo/s4_model_testing/model_testing.py:9:0: E0401: Unable to import 'addmo.util.definitions' (import-error)
addmo/s4_model_testing/model_testing.py:10:0: E0401: Unable to import 'addmo.s3_model_tuning.models.model_factory' (import-error)
addmo/s4_model_testing/model_testing.py:11:0: E0401: Unable to import 'sklearn.metrics' (import-error)
addmo/s4_model_testing/model_testing.py:12:0: E0401: Unable to import 'addmo.s2_data_tuning.config.data_tuning_config' (import-error)
addmo/s4_model_testing/model_testing.py:13:0: E0401: Unable to import 'addmo.s2_data_tuning.data_tuner_fixed' (import-error)
addmo/s4_model_testing/model_testing.py:14:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
addmo/s4_model_testing/model_testing.py:15:0: E0401: Unable to import 'addmo.util.data_handling' (import-error)
addmo/s4_model_testing/model_testing.py:16:0: E0401: Unable to import 'addmo.s5_insights.model_plots.scatter_plot' (import-error)
addmo/s4_model_testing/model_testing.py:17:0: E0401: Unable to import 'addmo.util.plotting_utils' (import-error)
addmo/s4_model_testing/model_testing.py:18:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
addmo/s4_model_testing/model_testing.py:20:0: C0116: Missing function or method docstring (missing-function-docstring)
addmo/s4_model_testing/model_testing.py:20:0: R0914: Too many local variables (21/15) (too-many-locals)
addmo/s4_model_testing/model_testing.py:20:15: W0622: Redefining built-in 'dir' (redefined-builtin)
addmo/s4_model_testing/model_testing.py:31:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
addmo/s4_model_testing/model_testing.py:47:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
addmo/s4_model_testing/model_testing.py:51:21: C0103: Variable name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s4_model_testing/model_testing.py:61:8: C0103: Variable name "xy" doesn't conform to snake_case naming style (invalid-name)
addmo/s4_model_testing/model_testing.py:62:8: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s4_model_testing/model_testing.py:63:8: C0103: Variable name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s4_model_testing/model_testing.py:75:0: C0116: Missing function or method docstring (missing-function-docstring)
addmo/s4_model_testing/model_testing.py:106:0: C0116: Missing function or method docstring (missing-function-docstring)
addmo/s4_model_testing/model_testing.py:126:4: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/s4_model_testing/model_testing.py:126:7: C0103: Variable name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/s4_model_testing/model_testing.py:126:4: W0612: Unused variable 'x' (unused-variable)
addmo/s4_model_testing/model_testing.py:11:0: C0411: third party import "from sklearn.metrics import root_mean_squared_error" should be placed before "from addmo.util.definitions import results_dir_data_tuning, results_dir" (wrong-import-order)
addmo/s4_model_testing/model_testing.py:12:0: C0412: Imports from package addmo are not grouped (ungrouped-imports)
************* Module load_save_utils
addmo/util/load_save_utils.py:95:0: C0305: Trailing newlines (trailing-newlines)
addmo/util/load_save_utils.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/util/load_save_utils.py:54:4: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
addmo/util/load_save_utils.py:62:0: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
addmo/util/load_save_utils.py:83:4: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
************* Module load_save
addmo/util/load_save.py:100:0: C0304: Final newline missing (missing-final-newline)
addmo/util/load_save.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/util/load_save.py:1:0: E0401: Unable to import 'pandas' (import-error)
addmo/util/load_save.py:5:0: E0401: Unable to import 'pydantic' (import-error)
addmo/util/load_save.py:7:0: W0404: Reimport 'datetime' (imported line 3) (reimported)
addmo/util/load_save.py:23:17: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
addmo/util/load_save.py:23:38: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
addmo/util/load_save.py:29:12: C0103: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
addmo/util/load_save.py:43:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
addmo/util/load_save.py:43:28: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
addmo/util/load_save.py:56:15: W0718: Catching too general exception Exception (broad-exception-caught)
addmo/util/load_save.py:55:12: C0103: Variable name "df" doesn't conform to snake_case naming style (invalid-name)
addmo/util/load_save.py:57:12: C0103: Variable name "df" doesn't conform to snake_case naming style (invalid-name)
addmo/util/load_save.py:61:8: C0103: Variable name "df" doesn't conform to snake_case naming style (invalid-name)
addmo/util/load_save.py:70:15: C0103: Argument name "df" doesn't conform to snake_case naming style (invalid-name)
addmo/util/load_save.py:82:0: C0116: Missing function or method docstring (missing-function-docstring)
addmo/util/load_save.py:83:4: C0103: Argument name "df" doesn't conform to snake_case naming style (invalid-name)
addmo/util/load_save.py:2:0: C0411: standard import "import json" should be placed before "import pandas as pd" (wrong-import-order)
addmo/util/load_save.py:3:0: C0411: standard import "import datetime" should be placed before "import pandas as pd" (wrong-import-order)
addmo/util/load_save.py:4:0: C0411: standard import "from pathlib import Path" should be placed before "import pandas as pd" (wrong-import-order)
addmo/util/load_save.py:6:0: C0411: standard import "from typing import Type, TypeVar, Union" should be placed before "import pandas as pd" (wrong-import-order)
addmo/util/load_save.py:7:0: C0411: standard import "import datetime" should be placed before "import pandas as pd" (wrong-import-order)
addmo/util/load_save.py:7:0: C0412: Imports from package datetime are not grouped (ungrouped-imports)
************* Module definitions
addmo/util/definitions.py:52:0: C0301: Line too long (102/100) (line-too-long)
addmo/util/definitions.py:62:0: C0301: Line too long (174/100) (line-too-long)
addmo/util/definitions.py:66:0: C0301: Line too long (121/100) (line-too-long)
addmo/util/definitions.py:83:0: C0301: Line too long (129/100) (line-too-long)
addmo/util/definitions.py:119:0: C0304: Final newline missing (missing-final-newline)
addmo/util/definitions.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/util/definitions.py:4:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
addmo/util/definitions.py:5:0: E0401: Unable to import 'addmo.s2_data_tuning.config.data_tuning_config' (import-error)
addmo/util/definitions.py:6:0: E0401: Unable to import 'addmo.s3_model_tuning.config.model_tuning_config' (import-error)
addmo/util/definitions.py:7:0: E0401: Unable to import 'addmo.s1_data_tuning_auto.config.data_tuning_auto_config' (import-error)
addmo/util/definitions.py:14:4: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
addmo/util/definitions.py:69:22: W0622: Redefining built-in 'dir' (redefined-builtin)
addmo/util/definitions.py:90:4: W0622: Redefining built-in 'dir' (redefined-builtin)
addmo/util/definitions.py:100:4: W0622: Redefining built-in 'dir' (redefined-builtin)
addmo/util/definitions.py:112:22: W0622: Redefining built-in 'dir' (redefined-builtin)
addmo/util/definitions.py:117:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
addmo/util/definitions.py:117:35: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
addmo/util/definitions.py:2:0: W0611: Unused import glob (unused-import)
************* Module plotting_utils
addmo/util/plotting_utils.py:29:0: C0305: Trailing newlines (trailing-newlines)
addmo/util/plotting_utils.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/util/plotting_utils.py:3:0: E0401: Unable to import 'pandas' (import-error)
addmo/util/plotting_utils.py:5:0: E0401: Unable to import 'pydantic' (import-error)
addmo/util/plotting_utils.py:23:0: C0116: Missing function or method docstring (missing-function-docstring)
addmo/util/plotting_utils.py:26:0: C0116: Missing function or method docstring (missing-function-docstring)
addmo/util/plotting_utils.py:4:0: C0411: standard import "from typing import Optional" should be placed before "import pandas as pd" (wrong-import-order)
addmo/util/plotting_utils.py:2:0: W0611: Unused import re (unused-import)
addmo/util/plotting_utils.py:3:0: W0611: Unused pandas imported as pd (unused-import)
addmo/util/plotting_utils.py:4:0: W0611: Unused Optional imported from typing (unused-import)
addmo/util/plotting_utils.py:5:0: W0611: Unused BaseModel imported from pydantic (unused-import)
addmo/util/plotting_utils.py:5:0: W0611: Unused Field imported from pydantic (unused-import)
addmo/util/plotting_utils.py:5:0: W0611: Unused create_model imported from pydantic (unused-import)
************* Module experiment_logger
addmo/util/experiment_logger.py:125:0: C0301: Line too long (115/100) (line-too-long)
addmo/util/experiment_logger.py:126:0: C0301: Line too long (116/100) (line-too-long)
addmo/util/experiment_logger.py:127:0: C0301: Line too long (119/100) (line-too-long)
addmo/util/experiment_logger.py:128:0: C0301: Line too long (120/100) (line-too-long)
addmo/util/experiment_logger.py:129:0: C0301: Line too long (118/100) (line-too-long)
addmo/util/experiment_logger.py:172:0: C0301: Line too long (111/100) (line-too-long)
addmo/util/experiment_logger.py:216:0: C0301: Line too long (119/100) (line-too-long)
addmo/util/experiment_logger.py:217:0: C0301: Line too long (120/100) (line-too-long)
addmo/util/experiment_logger.py:218:0: C0301: Line too long (123/100) (line-too-long)
addmo/util/experiment_logger.py:219:0: C0301: Line too long (124/100) (line-too-long)
addmo/util/experiment_logger.py:220:0: C0301: Line too long (122/100) (line-too-long)
addmo/util/experiment_logger.py:172:36: W0511: Todo: evtl. komplett löschen und auf normale speicher funktionen umstellen? (fixme)
addmo/util/experiment_logger.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/util/experiment_logger.py:4:0: E0401: Unable to import 'pandas' (import-error)
addmo/util/experiment_logger.py:5:0: E0401: Unable to import 'pandas' (import-error)
addmo/util/experiment_logger.py:6:0: E0401: Unable to import 'wandb' (import-error)
addmo/util/experiment_logger.py:7:0: E0401: Unable to import 'addmo.s3_model_tuning.models.abstract_model' (import-error)
addmo/util/experiment_logger.py:8:0: E0401: Unable to import 'addmo.util.load_save' (import-error)
addmo/util/experiment_logger.py:9:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
addmo/util/experiment_logger.py:10:0: E0401: Unable to import 'addmo.util.load_save_utils' (import-error)
addmo/util/experiment_logger.py:11:0: E0401: Unable to import 'addmo.s3_model_tuning.models.model_factory' (import-error)
addmo/util/experiment_logger.py:14:0: C0115: Missing class docstring (missing-class-docstring)
addmo/util/experiment_logger.py:17:4: C0116: Missing function or method docstring (missing-function-docstring)
addmo/util/experiment_logger.py:22:4: C0116: Missing function or method docstring (missing-function-docstring)
addmo/util/experiment_logger.py:27:4: C0116: Missing function or method docstring (missing-function-docstring)
addmo/util/experiment_logger.py:32:4: C0116: Missing function or method docstring (missing-function-docstring)
addmo/util/experiment_logger.py:37:4: C0116: Missing function or method docstring (missing-function-docstring)
addmo/util/experiment_logger.py:45:37: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
addmo/util/experiment_logger.py:57:0: C0115: Missing class docstring (missing-class-docstring)
addmo/util/experiment_logger.py:63:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
addmo/util/experiment_logger.py:164:47: C0103: Variable name "f" doesn't conform to snake_case naming style (invalid-name)
addmo/util/experiment_logger.py:148:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
addmo/util/experiment_logger.py:172:0: C0115: Missing class docstring (missing-class-docstring)
addmo/util/experiment_logger.py:178:4: W0222: Signature differs from overridden 'start_experiment' method (signature-differs)
addmo/util/experiment_logger.py:178:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
addmo/util/experiment_logger.py:238:12: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
addmo/util/experiment_logger.py:231:4: R1710: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
addmo/util/experiment_logger.py:273:8: W0612: Unused variable 'data_local' (unused-variable)
addmo/util/experiment_logger.py:5:0: W0611: Unused ExcelWriter imported from pandas (unused-import)
addmo/util/experiment_logger.py:9:0: W0611: Unused create_or_clean_directory imported from addmo.util.load_save_utils (unused-import)
************* Module data_handling
addmo/util/data_handling.py:4:0: C0304: Final newline missing (missing-final-newline)
addmo/util/data_handling.py:1:0: C0114: Missing module docstring (missing-module-docstring)
addmo/util/data_handling.py:1:0: C0116: Missing function or method docstring (missing-function-docstring)
addmo/util/data_handling.py:1:39: C0103: Argument name "xy" doesn't conform to snake_case naming style (invalid-name)
addmo/util/data_handling.py:2:4: C0103: Variable name "x" doesn't conform to snake_case naming style (invalid-name)
addmo/util/data_handling.py:3:4: C0103: Variable name "y" doesn't conform to snake_case naming style (invalid-name)
addmo/util/data_handling.py:1:0: R0801: Similar lines in 2 files
==carpet_plots:[174:199]
==plot_carpets_modelA:[133:157]
        features = regressor.metadata["features_ordered"]
        if rename_dict is not None:
            features = [rename_dict[feature] for feature in features]

        # Determine the shape of the output
        shape = next(
            arr.shape for arr in kwargs.values() if isinstance(arr, np.ndarray)
        )

        # Prepare input saved_plots
        input_data = pd.DataFrame(
            {feature: np.ravel(kwargs[feature]) for feature in features}
        )

        # Make prediction
        prediction = regressor.predict(input_data)

        # Reshape the prediction to match the input shape
        return prediction.reshape(shape)

    return pred_func

def plot_carpets_with_buckets(variables, measurements_data, target_values, regressor_func , bounds=None , combinations=None , defaults_dict=None ,num_buckets=4):

    # Define bounds (duplicate-code)
addmo/util/data_handling.py:1:0: R0801: Similar lines in 2 files
==carpet_plots:[113:130]
==plot_carpets_modelA:[74:93]
            norm1 = colors.Normalize(vmin=np.nanmin(Z1), vmax=np.nanmax(Z1))
            norm2 = colors.Normalize(vmin=np.nanmin(Z2), vmax=np.nanmax(Z2))

            Z1_greater = np.where(Z1 >= Z2, Z1, np.nan)
            Z1_smaller = np.where(Z1 <= Z2, Z1, np.nan)
            Z2_greater = np.where(Z2 >= Z1, Z2, np.nan)
            Z2_smaller = np.where(Z2 <= Z1, Z2, np.nan)

            # surface plots in correct order and normalization
            surf1 = ax.plot_surface(X, Y, Z1, cmap=surf1_cmap, visible=False, norm=norm1)
            surf2 = ax.plot_surface(X, Y, Z2, cmap=surf2_cmap, visible=False, norm=norm2)
            surf2_smaller = ax.plot_surface(X, Y, Z2_smaller, cmap=surf2_cmap, alpha=0.5, norm=norm2)
            surf1_smaller = ax.plot_surface(X, Y, Z1_smaller, cmap=surf1_cmap, alpha=0.5, norm=norm1)
            surf2_greater = ax.plot_surface(X, Y, Z2_greater, cmap=surf2_cmap, alpha=0.5, norm=norm2)
            surf1_greater = ax.plot_surface(X, Y, Z1_greater, cmap=surf1_cmap, alpha=0.5, norm=norm1)

        # Add this line to reverse the axis direction (duplicate-code)
addmo/util/data_handling.py:1:0: R0801: Similar lines in 2 files
==carpet_plots:[89:104]
==plot_carpets_modelA:[50:65]
        X, Y = np.meshgrid(grids[x_label], grids[y_label])

        # Create input arrays for prediction functions
        inputs = {}
        for var in variables:
            if var == x_label:
                inputs[var] = X
            elif var == y_label:
                inputs[var] = Y
            else:
                if defaults_dict == None:
                    inputs[var] = np.full_like(X, np.mean(grids[var]))
                else:
                    inputs[var] = np.full_like(X, defaults_dict[var])
 (duplicate-code)
addmo/util/data_handling.py:1:0: R0801: Similar lines in 2 files
==exe_recreate_data_tuning:[29:50]
==model_testing:[81:101]
    new_config = DataTuningAutoSetup(**saved_config_data)

    LocalLogger.directory = results_dir_data_tuning(new_config)
    LocalLogger.active = True
    WandbLogger.project = "addmo-test_data_auto_tuning"
    WandbLogger.directory = results_dir_data_tuning(new_config)
    WandbLogger.active = False

    ExperimentLogger.start_experiment(config=new_config)

    # Create a new tuner instance with the same tuning parameters
    new_tuner = DataTunerAuto(config=new_config)

    # Apply the same tuning process to the new data
    tuned_x_new = new_tuner.tune_auto()
    y_new = new_tuner.y

    tuned_xy_new = pd.concat([y_new, tuned_x_new], axis=1, join="inner").bfill()

    # Log the tuned system data (duplicate-code)
addmo/util/data_handling.py:1:0: R0801: Similar lines in 2 files
==exe_data_tuning_auto:[53:65]
==exe_data_tuning_fixed:[73:85]
    for fig in figures:
        fig.show()
    os.makedirs(LocalLogger.directory, exist_ok=True)
    for idx, fig in enumerate(figures):
        suffix = "_2weeks" if idx == 1 else ""
        plot_path = os.path.join(LocalLogger.directory, f"{file_name}{suffix}")
        save_pdf(fig, plot_path)
    print("Finished")

def exe_data_tuning_auto(user_input='y'):
    """Execute the system_data tuning process with user defined config."""
    # Path to the config file (duplicate-code)
addmo/util/data_handling.py:1:0: R0801: Similar lines in 2 files
==exe_data_tuning_fixed:[45:57]
==model_testing:[128:140]
    tuned_x = tuner.tune_fixed(xy_raw)
    ExperimentLogger.log({"x_tuned": tuned_x.iloc[[0, 1, 2, -3, -2, -1]]})

    # Merge target and features
    xy_tuned = tuned_x.join(y)
    ExperimentLogger.log({"xy_tuned": xy_tuned.iloc[[0, 1, 2, -3, -2, -1]]})

    # Drop NaNs
    xy_tuned = xy_tuned.dropna()
    ExperimentLogger.log({"xy_tuned": xy_tuned.iloc[[0, 1, 2, -3, -2, -1]]})

    # Log the tuned system_data (duplicate-code)
addmo/util/data_handling.py:1:0: R0801: Similar lines in 2 files
==exe_recreate_data_tuning:[32:41]
==model_testing:[114:123]
    LocalLogger.directory = results_dir_data_tuning(new_config)
    LocalLogger.active = True
    WandbLogger.project = "addmo-test_data_auto_tuning"
    WandbLogger.directory = results_dir_data_tuning(new_config)
    WandbLogger.active = False

    ExperimentLogger.start_experiment(config=new_config)

    #Using fixed config (duplicate-code)
addmo/util/data_handling.py:1:0: R0801: Similar lines in 2 files
==abstract_model:[143:196]
==experiment_logger:[17:41]
        pass

    @abstractmethod
    def set_params(self, **params):
        """
        Set the hyperparameters of the ML model.

        Args:
            **params: Variable length keyword arguments for hyperparameters.
        """
        pass

    @abstractmethod
    def get_params(self):
        """
        Get the hyperparameters of the ML model.

        Returns:
            A dictionary of the current hyperparameters.
        """
        pass

    @abstractmethod
    def optuna_hyperparameter_suggest(self, trial):
        """
        Suggest hyperparameters using Optuna for hyperparameter optimization.

        Args:
            trial: An Optuna trial object used to suggest hyperparameters.

        Returns:
            A dictionary of hyperparameters with Optuna distributions.
        """
        pass

    @abstractmethod
    def grid_search_hyperparameter(self):
        """
        Define the hyperparameters for grid search.

        Returns:
            A dictionary representing a hyperparameter grid for grid search.
        """
        pass

    @abstractmethod
    def default_hyperparameter(self):
        """
        Define the default hyperparameters of the model.

        Returns:
            A dictionary with a default set of hyperparameters.
        """ (duplicate-code)
addmo/util/data_handling.py:1:0: R0801: Similar lines in 2 files
==exe_data_tuning_auto:[45:52]
==exe_data_tuning_fixed:[64:72]
    saved_data_path = os.path.join(LocalLogger.directory, file_name + '.csv')
    data = pd.read_csv(saved_data_path, delimiter=",", index_col=0, encoding="latin1", header=0)
    config_path = os.path.join(LocalLogger.directory, "config.json")
    with open(config_path, 'r') as f:
        plot_config = json.load(f)

    # Plot tuned data
 (duplicate-code)

-----------------------------------
Your code has been rated at 2.09/10

